import { createClient } from "@supabase/supabase-js";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
function getUser(token:string){try{const p=token.split(".");if(p.length!==3)return null;const e=p[1].replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(p[1].length/4)*4,"=");return String(JSON.parse(atob(e))?.sub||"").trim()||null}catch{return null}}
const text=(v:unknown)=>String(v??"").trim(); const UF=(v:unknown)=>text(v).toUpperCase()||"N/I"; const label=(v:unknown,f:string)=>text(v)||f; const city=(p:any)=>text(p?.acting_city||p?.city||p?.municipality); const same=(a:unknown,b:unknown)=>text(a).localeCompare(text(b),"pt-BR",{sensitivity:"base"})===0; const days=(p:string)=>({"7d":7,"30d":30,"90d":90,"365d":365}[p]||0);
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders}); if(!["GET","POST"].includes(req.method))return json({error:"method_not_allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(!url||!key)return json({error:"server_configuration_error"},500); const auth=req.headers.get("Authorization"); if(!auth?.startsWith("Bearer "))return json({error:"missing_authorization"},401); const userId=getUser(auth.slice(7).trim()); if(!userId)return json({error:"invalid_session"},401);
 const admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}}); const {data:profile,error:pe}=await admin.from("admin_profiles").select("id,role,active").eq("id",userId).maybeSingle(); if(pe)return json({error:"authorization_check_failed"},500); if(!profile||profile.active===false||!["admin","superadmin"].includes(text(profile.role).toLowerCase()))return json({error:"admin_access_required"},403);
 let f:any={};if(req.method==="POST"){try{f=await req.json()}catch{f={}}} const selectedUf=text(f.uf).toUpperCase(),selectedMunicipality=text(f.municipality),period=["7d","30d","90d","365d"].includes(text(f.period))?text(f.period):"all",employment=text(f.employment),teaching=text(f.teaching),activity=["active","inactive"].includes(text(f.activity))?text(f.activity):"all",since=days(period)?Date.now()-days(period)*86400000:0;
 const {data:snapshot,error:se}=await admin.rpc("enat_hub_neurodrive_snapshot"); if(se)return json({error:"hub_snapshot_read_failed"},500); if(!snapshot||snapshot.error==="hub_source_not_registered")return json({error:"hub_source_not_registered"},500); if(snapshot.error==="hub_source_disabled")return json({error:"hub_source_disabled"},403);
 const raw=Array.isArray(snapshot.assessments)?snapshot.assessments:[]; const [pr,sr,lr,ir]=await Promise.all([admin.from("ai_profiles").select("id,created_at,uf,acting_city,city,credential,credential_uf,employment_type,teaching_type").in("role",["instructor","instrutor"]),admin.from("ai_students").select("id",{count:"exact",head:true}),admin.from("ai_lessons").select("id,user_id,status,created_at",{count:"exact"}),admin.from("enat_instructors").select("id,active",{count:"exact"})]); if(pr.error||sr.error||lr.error||ir.error)return json({error:"administrative_snapshot_read_failed"},500);
 const allProfiles=pr.data||[],lessons=lr.data||[],activeUsers=new Set(lessons.filter(l=>l.status!=="cancelled").map(l=>l.user_id)); const match=(p:any)=>{if(selectedUf&&UF(p.uf||p.credential_uf)!==selectedUf)return false;if(selectedMunicipality&&!same(city(p),selectedMunicipality))return false;if(employment&&!same(p.employment_type,employment))return false;if(teaching&&!same(p.teaching_type,teaching))return false;if(activity==="active"&&!activeUsers.has(p.id))return false;if(activity==="inactive"&&activeUsers.has(p.id))return false;if(since&&new Date(p.created_at).getTime()<since)return false;return true}; const profiles=allProfiles.filter(match),profileIds=new Set(profiles.map(p=>p.id)),scopedActive=new Set(lessons.filter(l=>l.status!=="cancelled"&&profileIds.has(l.user_id)).map(l=>l.user_id));
 const assessmentHasMunicipality=raw.some((r:any)=>text(r.municipality||r.city||r.acting_city)); const assessments=raw.filter((r:any)=>{if(selectedUf&&UF(r.uf)!==selectedUf)return false;if(selectedMunicipality&&(!assessmentHasMunicipality||!same(r.municipality||r.city||r.acting_city,selectedMunicipality)))return false;if(since&&new Date(r.observed_at).getTime()<since)return false;return true}); const scores=assessments.map((r:any)=>Number(r.total_score)).filter(Number.isFinite); const avg=scores.length?Number((scores.reduce((a:number,b:number)=>a+b,0)/scores.length).toFixed(2)):null;
 const aggregate=(rows:any[],key:(r:any)=>string)=>{const m=new Map<string,number>();for(const r of rows){const k=key(r)||"N/I";m.set(k,(m.get(k)||0)+1)}return[...m.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name,"pt-BR"))};
 const ufDist=aggregate(assessments,r=>UF(r.uf)).map(x=>({uf:x.name,assessments:x.count})),riskDist=aggregate(assessments,r=>label(r.risk_class,"Não classificado")).map(x=>({risk:x.name,count:x.count})),instrUf=aggregate(profiles,p=>UF(p.uf||p.credential_uf)).map(x=>({uf:x.name,instructors:x.count}));
 const states=new Map<string,{uf:string,instructors:number,municipalities:Map<string,number>}>(); for(const p of profiles){const u=UF(p.uf||p.credential_uf),c=city(p),s=states.get(u)||{uf:u,instructors:0,municipalities:new Map<string,number>()};s.instructors++;if(c)s.municipalities.set(c,(s.municipalities.get(c)||0)+1);states.set(u,s)} const locality=[...states.values()].sort((a,b)=>b.instructors-a.instructors).map(s=>({uf:s.uf,instructors:s.instructors,municipalities:[...s.municipalities.entries()].map(([name,instructors])=>({name,instructors})).sort((a,b)=>b.instructors-a.instructors||a.name.localeCompare(b.name,"pt-BR"))}));
 const emp=aggregate(profiles,p=>label(p.employment_type,"Não informado")),teach=aggregate(profiles,p=>label(p.teaching_type,"Não informado")),complete=profiles.filter(p=>Boolean(p.uf&&city(p)&&p.credential&&p.credential_uf)).length; const recent=[...profiles].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,10).map(p=>({created_at:p.created_at,uf:UF(p.uf||p.credential_uf),municipality:city(p)||null,profile_complete:Boolean(p.uf&&city(p)&&p.credential&&p.credential_uf),has_activity:activeUsers.has(p.id)}));
 const instTotal=ir.count||0,instActive=(ir.data||[]).filter(x=>x.active!==false).length; return json({source:text(snapshot.source)||"assistenteinstrutorv6",source_name:text(snapshot.source_name)||"AssistenteInstrutorV6 → CMNT",generated_at:new Date().toISOString(),privacy:{pii_excluded:true,individual_records_excluded:true},filters:{uf:selectedUf,municipality:selectedMunicipality,period,employment,teaching,activity},locality:{selected_uf:selectedUf||null,selected_municipality:selectedMunicipality||null,assessment_locality_supported:assessmentHasMunicipality},totals:{assessments:assessments.length,scored_assessments:scores.length,average_score:avg,ufs:ufDist.length},uf_distribution:ufDist,risk_distribution:riskDist,recent:assessments.slice(0,10).map((r:any)=>({observed_at:r.observed_at,uf:r.uf,municipality:r.municipality||r.city||null,age_band:r.age_band,cnh_category:r.cnh_category,instrument:r.instrument,instrument_version:r.instrument_version,total_score:r.total_score,risk_class:r.risk_class})),instructor_intelligence:{registered:profiles.length,total_registered_unfiltered:allProfiles.length,registrations_last_7_days:allProfiles.filter(p=>new Date(p.created_at).getTime()>=Date.now()-7*86400000&&match(p)).length,registrations_last_30_days:allProfiles.filter(p=>new Date(p.created_at).getTime()>=Date.now()-30*86400000&&match(p)).length,with_activity:scopedActive.size,without_activity:Math.max(0,profiles.length-scopedActive.size),profile_complete:complete,profile_completion_rate:profiles.length?Number((complete/profiles.length*100).toFixed(1)):0,states:new Set(profiles.map(p=>UF(p.uf||p.credential_uf))).size,municipalities:new Set(profiles.map(city).filter(Boolean)).size,instructor_uf_distribution:instrUf,locality_distribution:locality,employment_distribution:emp,teaching_distribution:teach,recent_registrations:recent},platform_intelligence:{students:sr.count||0,lessons:lessons.filter(l=>l.status!=="cancelled"&&(!since||new Date(l.created_at).getTime()>=since)&&profileIds.has(l.user_id)).length,lessons_all:lessons.filter(l=>l.status!=="cancelled").length,institutional_instructors:instTotal,institutional_active_instructors:instActive}});
});