import {useEffect,useState} from "react";
import {supabase} from "../lib/supabaseClient";

const fields=[
 ["site_title","Nome do site"],["site_description","Descrição do site"],["neuro_logo_url","Logo Neurociência Aplicada ao Trânsito"],["enat_logo_url","Logo ENAT"],["contact_email","E-mail público"],["contact_phone","Telefone / WhatsApp"],["instagram_url","Instagram"],["linkedin_url","LinkedIn"],["youtube_url","YouTube"]
];
const empty={site_title:"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",site_description:"Ciência, educação e humanização para um trânsito mais seguro.",neuro_logo_url:"",enat_logo_url:"",contact_email:"",contact_phone:"",instagram_url:"",linkedin_url:"",youtube_url:""};
const imageKeys=new Set(["neuro_logo_url","enat_logo_url"]);
const inputStyle={width:"100%",boxSizing:"border-box",padding:12,borderRadius:10,border:"1px solid #365163",background:"#07111b",color:"#eaf6ff"};
async function uploadImage(file){if(!file) return "";if(!file.type.startsWith("image/")) throw new Error("Selecione uma imagem válida.");if(file.size>15*1024*1024) throw new Error("A imagem deve ter no máximo 15 MB.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`portal/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("enat-public-assets").upload(path,file,{upsert:false,contentType:file.type,cacheControl:"31536000"});if(error) throw error;return supabase.storage.from("enat-public-assets").getPublicUrl(path).data.publicUrl;}
function ImageField({label,value,onChange}){const [busy,setBusy]=useState(false);const [error,setError]=useState("");const choose=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");try{onChange(await uploadImage(file))}catch(err){setError(err.message||"Falha ao enviar imagem.")}finally{setBusy(false);e.target.value=""}};return <div className="config-image-field"><span>{label}</span><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/gif" onChange={choose} disabled={busy} style={{...inputStyle,padding:9}}/><small>{busy?"Enviando imagem…":"PNG, JPG, WEBP, SVG ou GIF · máximo 15 MB"}</small>{value&&<img src={value} alt="Pré-visualização"/>}{error&&<div className="config-error">{error}</div>}<input value={value||""} onChange={e=>onChange(e.target.value)} placeholder="Ou informe uma URL pública" style={inputStyle}/></div>}
export function ConfiguracaoPortalENAT(){const [form,setForm]=useState(empty),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");const set=(k,v)=>setForm(x=>({...x,[k]:v}));useEffect(()=>{(async()=>{try{const {data,error}=await supabase.from("enat_public_content").select("id,metadata").eq("section_key","site.settings").maybeSingle();if(error)throw error;if(data?.metadata)setForm({...empty,...data.metadata});}catch(e){setMsg(e.message||"Não foi possível carregar as configurações.")}finally{setBusy(false)}})()},[]);const save=async()=>{setSaving(true);setMsg("");try{const {data:row,error:rowError}=await supabase.from("enat_public_content").select("id").eq("section_key","site.settings").maybeSingle();if(rowError)throw rowError;if(!row?.id)throw new Error("Configuração site.settings não encontrada.");const {data,error}=await supabase.functions.invoke("manage-public-content",{body:{action:"update",id:row.id,content:{content_type:"settings",section_key:"site.settings",title:null,subtitle:null,body:null,metadata:form,sort_order:1,published:true}}});if(error)throw error;if(data?.error)throw new Error(data.error);setMsg("Configurações salvas com sucesso.")}catch(e){setMsg(e.message||"Erro ao salvar.")}finally{setSaving(false)}};if(busy)return <main className="config-portal"><div className="config-shell">Carregando configurações…</div></main>;return <main className="config-portal"><div className="config-shell"><div className="config-eyebrow">CENTRAL ENAT HSI</div><h1>Configurações do Portal Público</h1><p className="config-intro">Agora as imagens podem ser anexadas diretamente pelo computador ou celular. A URL pública continua disponível como alternativa.</p><section className="config-panel">{fields.map(([key,label])=>imageKeys.has(key)?<ImageField key={key} label={label} value={form[key]} onChange={v=>set(key,v)}/>:<label className="config-field" key={key}><span>{label}</span><input value={form[key]||""} onChange={e=>set(key,e.target.value)} placeholder={key.endsWith("_url")?"https://...":""} style={inputStyle}/></label>)}{msg&&<div className="config-message">{msg}</div>}<div className="config-actions"><button onClick={save} disabled={saving}>{saving?"Salvando…":"Salvar configurações"}</button><button className="secondary" onClick={()=>window.open("/portal","_blank")}>🌐 Abrir portal</button></div></section></div></main>}