import React,{useEffect,useMemo,useState} from "react";
import {listCertificates,listCourses,listStudents,listInstructors} from "../lib/certificatesApi";
import "./DashboardENAT.css";
export function DashboardENAT(){
 const [data,setData]=useState({certificates:[],courses:[],students:[],instructors:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const [c,co,s,i]=await Promise.allSettled([listCertificates(),listCourses(),listStudents(),listInstructors()]);const next={certificates:c.status==="fulfilled"?(c.value?.certificates||[]):[],courses:co.status==="fulfilled"?(co.value?.courses||[]):[],students:s.status==="fulfilled"?(s.value?.students||[]):[],instructors:i.status==="fulfilled"?(i.value?.instructors||[]):[]};const errs=[c,co,s,i].filter(x=>x.status==="rejected").map(x=>x.reason?.message||"Falha ao carregar um indicador");setData(next);if(errs.length)setError(errs.join(" • "));setLoading(false)};
 useEffect(()=>{load()},[]); const activeStudents=data.students.filter(x=>x.active!==false); const activeCourses=data.courses.filter(x=>x.active!==false); const activeTeachers=data.instructors.filter(x=>x.active!==false); const certValid=data.certificates.filter(x=>String(x.status||"").toLowerCase()!=="cancelado");
 const studentStats=useMemo(()=>({em_espera:activeStudents.filter(x=>x.status==="em_espera").length,concluindo:activeStudents.filter(x=>x.status==="concluindo").length,concluiu:activeStudents.filter(x=>x.status==="concluiu").length}),[activeStudents]);
 const courseStats=useMemo(()=>activeCourses.map(c=>({name:c.name,count:activeStudents.filter(s=>s.course_id===c.id).length})).sort((a,b)=>b.count-a.count),[activeCourses,activeStudents]);
 const recent=useMemo(()=>[...certValid].sort((a,b)=>new Date(b.issued_at||b.created_at||0)-new Date(a.issued_at||a.created_at||0)).slice(0,8),[certValid]); const max=Math.max(1,...courseStats.map(x=>x.count));
 return <main className="dashboard-enat"><header className="dash-head"><div><div className="dash-eyebrow">CENTRAL ENAT HSI · GESTÃO</div><h1>Dashboard ENAT</h1><p>Visão geral de alunos, cursos, docentes e certificados.</p></div><button onClick={load} disabled={loading}>{loading?"Atualizando…":"↻ Atualizar"}</button></header>{error&&<div className="dash-error">{error}</div>}
 <section className="dash-cards"><article><span>ALUNOS ATIVOS</span><strong>{activeStudents.length}</strong><small>{studentStats.concluindo} em andamento</small></article><article><span>CURSOS ATIVOS</span><strong>{activeCourses.length}</strong><small>Banco de Cursos</small></article><article><span>DOCENTES</span><strong>{activeTeachers.length}</strong><small>Corpo docente ENAT</small></article><article><span>CERTIFICADOS</span><strong>{certValid.length}</strong><small>Registros emitidos</small></article></section>
 <section className="dash-grid"><article className="dash-panel"><div className="panel-title"><div><span>ACOMPANHAMENTO</span><h2>Situação dos alunos</h2></div></div><div className="status-grid"><div><b>{studentStats.em_espera}</b><span>Em espera</span></div><div><b>{studentStats.concluindo}</b><span>Concluindo</span></div><div><b>{studentStats.concluiu}</b><span>Concluíram</span></div></div></article><article className="dash-panel"><div className="panel-title"><div><span>DISTRIBUIÇÃO</span><h2>Alunos por curso</h2></div></div><div className="bars">{courseStats.slice(0,8).map(x=><div className="bar-row" key={x.name}><div><span title={x.name}>{x.name}</span><b>{x.count}</b></div><i><em style={{width:`${Math.round(x.count/max*100)}%`}}/></i></div>)}{!courseStats.length&&<p className="muted">Nenhum curso ativo encontrado.</p>}</div></article></section>
 <section className="dash-panel"><div className="panel-title"><div><span>ÚLTIMAS EMISSÕES</span><h2>Certificados recentes</h2></div></div><div className="dash-table"><div className="dash-row dash-row-head"><span>Código</span><span>Aluno</span><span>Curso</span><span>Carga</span><span>Data</span></div>{recent.map(c=><div className="dash-row" key={c.id||c.code}><span><b>{c.code}</b></span><span>{c.student_name}</span><span>{c.course_name}</span><span>{c.hours}h</span><span>{c.end_date?new Date(`${c.end_date}T12:00:00`).toLocaleDateString("pt-BR"):"—"}</span></div>)}{!recent.length&&<p className="muted">Nenhum certificado emitido.</p>}</div></section>
 <section className="dash-shortcuts"><button onClick={()=>location.href="/alunos"}>👥 Gerenciar alunos</button><button onClick={()=>location.href="/cursos/admin"}>📚 Banco de cursos</button><button onClick={()=>location.href="/emissor"}>🖨️ Emitir certificado</button><button onClick={()=>location.href="/docente-enat"}>🎓 Certificado DOCENTE ENAT</button></section></main>;
}
