import React,{useEffect,useMemo,useState} from "react";
import {jsPDF} from "jspdf";
import QRCode from "qrcode";
import {issueCertificate,listCourses,listInstructors} from "../lib/certificatesApi";
import {syncCoursesWithLocalAssignments} from "../lib/courseAssignmentsSync";
import "./DocenteENAT.css";

const BRAND_DB="enat-certificate-brand",BRAND_STORE="assets";
const openDB=()=>new Promise((res,rej)=>{if(!indexedDB)return rej();const r=indexedDB.open(BRAND_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(BRAND_STORE))r.result.createObjectStore(BRAND_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const getBrands=async()=>{try{const db=await openDB();return await new Promise(resolve=>{const q=db.transaction(BRAND_STORE,"readonly").objectStore(BRAND_STORE).get("logos");q.onsuccess=()=>resolve(q.result||{});q.onerror=()=>resolve({})})}catch{return {}}};
const digits=v=>String(v||"").replace(/\D/g,"");
const hash=async v=>[...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))].map(b=>b.toString(16).padStart(2,"0")).join("");
const days=(a,b)=>a&&b?Math.floor((new Date(`${b}T00:00:00`)-new Date(`${a}T00:00:00`))/86400000)+1:0;
const br=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR"):"";
const imgSize=d=>new Promise(resolve=>{if(!d)return resolve({w:1,h:1});const i=new Image();i.onload=()=>resolve({w:i.naturalWidth||1,h:i.naturalHeight||1});i.onerror=()=>resolve({w:1,h:1});i.src=d});
const addImg=async(doc,d,x,y,mw,mh)=>{if(!d)return;try{const {w,h}=await imgSize(d),r=Math.min(mw/w,mh/h),ww=w*r,hh=h*r;doc.addImage(d,String(d).toLowerCase().includes("jpeg")?"JPEG":"PNG",x+(mw-ww)/2,y+(mh-hh)/2,ww,hh,undefined,"FAST")}catch{}};

export function DocenteENAT(){
 const [teachers,setTeachers]=useState([]),[courses,setCourses]=useState([]),[teacherId,setTeacherId]=useState(""),[courseId,setCourseId]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[brand,setBrand]=useState({});
 useEffect(()=>{(async()=>{const [i,c,b]=await Promise.allSettled([listInstructors(),listCourses(),getBrands()]);if(i.status==="fulfilled")setTeachers((i.value?.instructors||[]).filter(x=>x.active!==false));if(c.status==="fulfilled"){const dbCourses=(c.value?.courses||[]).filter(x=>x.active!==false);try{const synced=await syncCoursesWithLocalAssignments(dbCourses);setCourses(synced.courses);if(synced.changed)setMsg("As atribuições docentes do emissor foram sincronizadas com o Banco de Cursos e o Supabase.")}catch(e){setCourses(dbCourses);setMsg(`Cursos carregados, mas a sincronização docente não foi concluída: ${e.message||"falha"}`)}}else setMsg(`Cursos: ${c.reason?.message||"falha ao carregar"}`);if(b.status==="fulfilled")setBrand(b.value||{})})()},[]);
 const teacher=teachers.find(x=>x.id===teacherId);const course=courses.find(x=>x.id===courseId);
 const assigned=useMemo(()=>{if(!teacher||!course)return[];return (course.modules||[]).flatMap((m,mi)=>(m.lessons||[]).filter(l=>String(l.teacherId||l.teacher_id||l.teacher?.id||"").trim()===String(teacher.id)).map((l,li)=>({module:m.title,lesson:l.name,hours:Number(l.hours||0),mi,li})))},[teacher,course]);
 const totalHours=assigned.reduce((a,x)=>a+x.hours,0); const minDays=Math.max(1,Math.ceil(totalHours/24*7));
 const emit=async()=>{setMsg("");if(!teacher)return setMsg("Selecione o docente ENAT.");if(!course)return setMsg("Selecione o curso.");if(!assigned.length)return setMsg("Este docente ainda não está vinculado a nenhuma aula deste curso. Atribua o docente no cadastro do curso.");if(!start||!end)return setMsg(`Informe o período de atuação. Para ${totalHours} horas, o período mínimo calculado é de ${minDays} dias.`);if(days(start,end)<minDays)return setMsg(`Período insuficiente: ${totalHours} horas exigem no mínimo ${minDays} dias.`);setBusy(true);try{const subjects=[{title:course.name,hours:totalHours,lessons:assigned.map(x=>({name:x.lesson,hours:x.hours,teacher:{id:teacher.id,name:teacher.name,qualification:teacher.qualification,formation:teacher.formation}}))}];const r=await issueCertificate({student_name:teacher.name,student_credential:null,student_signature:null,cpf_hash:await hash(`DOCENTE_ENAT:${teacher.id}`),course_name:course.name,course_nature:"Certificado de Atuação Docente ENAT",hours:totalHours,subjects,completion_date:end,start_date:start,end_date:end,responsible:course.responsible||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",author:course.author||"Vilmar Becker",institution_name:course.responsible||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",institution_cnpj:"",responsible_role:course.responsibleRole||course.responsible_role||"Responsável Técnico",modality:course.modality||"Online"});await makePDF(r.certificate);setMsg(`Certificado DOCENTE ENAT ${r.certificate.code} emitido com sucesso.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const makePDF=async c=>{const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"}),W=297,H=210;doc.setFillColor(8,14,24);doc.rect(0,0,W,H,"F");doc.setDrawColor(70,190,240);doc.setLineWidth(1.2);doc.rect(10,10,W-20,H-20);await addImg(doc,brand.enatLogo,18,15,42,42);await addImg(doc,brand.neuroLogo,237,15,42,42);doc.setTextColor(210,240,250);doc.setFont("helvetica","bold");doc.setFontSize(31);doc.text("DOCENTE ENAT",W/2,48,{align:"center"});doc.setFontSize(12);doc.setFont("helvetica","normal");doc.text("CERTIFICADO DE ATUAÇÃO DOCENTE",W/2,58,{align:"center"});doc.setFontSize(23);doc.setFont("helvetica","bold");doc.text(c.student_name,W/2,82,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(12);doc.text(`${teacher?.qualification||"Docente"} • ${teacher?.formation||""}`,W/2,92,{align:"center"});const text=`Certificamos que o(a) profissional acima identificado(a) integrou o corpo docente ENAT e atuou como docente no curso ${c.course_name}, no período de ${br(c.start_date)} a ${br(c.end_date)}, com participação correspondente a ${c.hours} horas de atividades docentes.`;doc.setFontSize(13);doc.text(text,W/2,110,{align:"center",maxWidth:238,lineHeightFactor:1.45});doc.setFont("helvetica","bold");doc.setFontSize(13);doc.text(`${c.hours} horas • ${c.modality||"Online"}`,W/2,140,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(9.5);doc.text(`Registro: ${c.code}`,20,151);doc.text(`Responsável: ${c.responsible||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito"}`,20,158);const qr=await QRCode.toDataURL(`${window.location.origin}/validar/${c.code}`,{margin:1,width:180});doc.addImage(qr,"PNG",247,143,28,28);doc.setDrawColor(160,190,200);doc.line(92,180,205,180);doc.setFont("helvetica","bold");doc.setFontSize(12);doc.text(c.author||"Vilmar Becker",148.5,188,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(8);doc.text("Responsável pelo ENAT",148.5,194,{align:"center"});doc.setFontSize(7);doc.text("Validação pública por QR Code",261,174,{align:"center"});doc.text("Documento comprobatório de atuação docente no âmbito do ENAT; não corresponde a título acadêmico.",W/2,202,{align:"center"});doc.save(`${c.code}_DOCENTE_ENAT_${String(c.student_name).replace(/[^a-z0-9]+/gi,"_")}.pdf`)};
 return <main className="docente-enat"><header><div><div className="docente-eyebrow">CENTRAL ENAT HSI · CORPO DOCENTE</div><h1>Certificado DOCENTE ENAT</h1><p>Emita o certificado de atuação docente a partir dos professores e cursos já cadastrados.</p></div><div className="docente-badge">DOCENTE ENAT</div></header><section className="docente-grid"><article className="docente-card"><h2>Dados da atuação</h2><label>Docente cadastrado<select value={teacherId} onChange={e=>{setTeacherId(e.target.value);setCourseId("")}}><option value="">Selecione um docente</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name} — {t.qualification}</option>)}</select></label>{teacher&&<div className="teacher-info"><strong>{teacher.name}</strong><span>{teacher.qualification} • {teacher.formation}</span></div>}<label>Curso cadastrado<select value={courseId} onChange={e=>setCourseId(e.target.value)} disabled={!teacher}><option value="">Selecione o curso</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name} — {c.code}</option>)}</select></label>{course&&<div className="assignment"><strong>{totalHours} horas atribuídas</strong><span>{assigned.length} aula(s) vinculada(s) ao docente</span>{assigned.slice(0,6).map((x,i)=><small key={i}>{x.module} · {x.lesson} · {x.hours}h</small>)}{assigned.length>6&&<small>+ {assigned.length-6} aula(s)</small>}</div>}<div className="date-grid"><label>Início<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fim<input type="date" min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="docente-summary"><span>Tipo</span><strong>DOCENTE ENAT</strong><span>Período mínimo calculado: {minDays} dia(s)</span></div><button className="emit-docente" onClick={emit} disabled={busy}>{busy?"Emitindo…":"Emitir certificado DOCENTE ENAT"}</button>{msg&&<div className="docente-msg">{msg}</div>}</article><article className="docente-card side"><h2>Como funciona</h2><div className="steps"><div><b>01</b><span>Selecione o docente cadastrado.</span></div><div><b>02</b><span>Selecione o curso em que ele está vinculado às aulas.</span></div><div><b>03</b><span>O sistema calcula automaticamente as horas docentes.</span></div><div><b>04</b><span>Informe o período e gere o PDF com QR Code.</span></div></div><div className="legal-note"><strong>Natureza documental</strong><p>O documento comprova a atuação docente no âmbito do ENAT. Não é diploma, certificado de pós-graduação ou título acadêmico.</p></div></article></section></main>;
}
