import {useEffect,useMemo,useState} from "react";
import {supabase} from "../lib/supabaseClient";
const edge="manage-hsi-email";
const call=async(body)=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sessão administrativa expirada.");const {data,error}=await supabase.functions.invoke(edge,{body,headers:{Authorization:"Bearer "+session.access_token}});if(error)throw error;if(data?.error)throw new Error(data.error);return data;};
const btn={padding:"9px 13px",borderRadius:7,border:"1px solid #31506b",background:"#14283b",color:"#e6f1fa",cursor:"pointer"};
const primary={...btn,background:"#82c8f7",color:"#07111b",fontWeight:800};
const input={width:"100%",boxSizing:"border-box",padding:11,borderRadius:7,border:"1px solid #31506b",background:"#07111b",color:"#e6f1fa"};
function Composer({mailboxes,selected,onClose,onSent}){
 const [from,setFrom]=useState(selected?.mailbox?.address||mailboxes[0]?.address||"");const [to,setTo]=useState(selected?.from_address||"");const [cc,setCc]=useState("");const [subject,setSubject]=useState(selected?.subject?"Re: "+selected.subject.replace(/^Re:\s*/i,""):"");const [text,setText]=useState(selected?"\n\n--- Mensagem original ---\n"+(selected.text_body||""):"");const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const send=async(e)=>{e.preventDefault();setBusy(true);setError("");try{const data=await call({action:"send",from,to,cc,subject,text,in_reply_to:selected?.message_id||null,references_header:selected?.references_header?(selected.references_header+" "+(selected.message_id||"")).trim():(selected?.message_id||null)});onSent(data.message);}catch(err){setError(err.message||"Não foi possível enviar.")}finally{setBusy(false)}};
 return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.78)",display:"grid",placeItems:"center",padding:20,zIndex:100}}><form onSubmit={send} style={{background:"#0d1b29",border:"1px solid #31506b",borderRadius:12,width:"min(820px,100%)",maxHeight:"92vh",overflow:"auto",padding:25}}>
 <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{color:"#82c8f7",fontSize:12,fontWeight:800,letterSpacing:1.5}}>E-MAIL HSI-DOTH-PG</div><h2 style={{margin:"6px 0 18px"}}>{selected?"Responder mensagem":"Nova mensagem"}</h2></div><button type="button" onClick={onClose} style={btn}>Fechar</button></div>
 <div style={{display:"grid",gap:12}}><label>De<select value={from} onChange={e=>setFrom(e.target.value)} style={{...input,marginTop:6}}>{mailboxes.map(m=><option key={m.id} value={m.address}>{m.display_name+" — "+m.address}</option>)}</select></label><label>Para<input value={to} onChange={e=>setTo(e.target.value)} placeholder="destinatario@exemplo.com" style={{...input,marginTop:6}}/></label><label>Cc<input value={cc} onChange={e=>setCc(e.target.value)} placeholder="Opcional" style={{...input,marginTop:6}}/></label><label>Assunto<input value={subject} onChange={e=>setSubject(e.target.value)} style={{...input,marginTop:6}}/></label><label>Mensagem<textarea rows={14} value={text} onChange={e=>setText(e.target.value)} style={{...input,marginTop:6,resize:"vertical",lineHeight:1.5}}/></label>{error&&<div style={{padding:10,border:"1px solid #754848",background:"#24171b",color:"#ffb4b4"}}>{error}</div>}<div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" onClick={onClose} style={btn}>Cancelar</button><button disabled={busy} type="submit" style={primary}>{busy?"Enviando…":"✉️ Enviar"}</button></div></div>
 </form></div>;
}
export function EmailHSIAdmin(){
 const [mailboxes,setMailboxes]=useState([]),[messages,setMessages]=useState([]),[folder,setFolder]=useState("inbox"),[mailbox,setMailbox]=useState("all"),[selected,setSelected]=useState(null),[compose,setCompose]=useState(null),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const loadMailboxes=async()=>{try{setMailboxes((await call({action:"mailboxes"})).mailboxes||[])}catch(e){setMsg(e.message)}};
 const load=async()=>{setBusy(true);try{const data=await call({action:"list",folder});let rows=data.messages||[];if(mailbox!=="all")rows=rows.filter(r=>r.mailbox_id===mailbox);if(search.trim()){const q=search.toLowerCase();rows=rows.filter(r=>[r.subject,r.from_address,r.from_name,...(r.to_addresses||[])].filter(Boolean).join(" ").toLowerCase().includes(q))}setMessages(rows)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 useEffect(()=>{loadMailboxes()},[]);useEffect(()=>{load()},[folder,mailbox]);
 const unread=useMemo(()=>messages.filter(m=>!m.read_at&&m.folder==="inbox").length,[messages]);
 const open=async(row)=>{try{const data=await call({action:"read",id:row.id});setSelected(data.message);setMessages(old=>old.map(m=>m.id===row.id?{...m,read_at:data.message.read_at}:m))}catch(e){setMsg(e.message)}};
 const status=async(id,next)=>{try{await call({action:"status",id,folder:next});setSelected(null);await load()}catch(e){setMsg(e.message)}};
 const remove=async(id)=>{if(!confirm("Mover esta mensagem para a lixeira?"))return;await status(id,"trash")};
 return <main style={{minHeight:"100vh",background:"#07111b",color:"#e6f1fa",padding:"105px 28px 50px",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1280,margin:"auto"}}>
 <div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"center",flexWrap:"wrap"}}><div><div style={{color:"#82c8f7",fontSize:12,fontWeight:800,letterSpacing:2}}>CENTRAL ENAT HSI</div><h1 style={{margin:"8px 0"}}>📧 E-mail HSI-DOTH-PG</h1><p style={{color:"#9db1c1",margin:0}}>Caixa de mensagens própria do portal administrativo.</p></div><button onClick={()=>setCompose({})} style={primary}>✉️ Nova mensagem</button></div>
 <div style={{display:"grid",gridTemplateColumns:"220px 1fr",gap:18,marginTop:24}}><aside style={{display:"grid",gap:8,alignContent:"start"}}>{[["inbox","📥 Entrada"],["sent","📤 Enviados"],["archive","🗄 Arquivados"],["trash","🗑 Lixeira"]].map(([k,l])=><button key={k} onClick={()=>setFolder(k)} style={{...btn,textAlign:"left",background:folder===k?"#1d3850":"#0d1b29"}}>{l}{k==="inbox"&&unread>0?" ("+unread+")":""}</button>)}<div style={{marginTop:10,padding:12,border:"1px solid #203b52",borderRadius:8,background:"#0d1b29"}}><strong>Setores</strong><select value={mailbox} onChange={e=>setMailbox(e.target.value)} style={{...input,marginTop:8}}><option value="all">Todos</option>{mailboxes.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select></div></aside>
 <section><div style={{display:"flex",gap:8,marginBottom:12}}><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Pesquisar remetente, assunto ou endereço…" style={input}/><button onClick={load} style={btn}>Pesquisar</button></div>{msg&&<div style={{padding:11,marginBottom:12,border:"1px solid #754848",background:"#24171b",color:"#ffb4b4"}}>{msg}</div>}<div style={{display:"grid",gap:8}}>{messages.map(m=><button key={m.id} onClick={()=>open(m)} style={{textAlign:"left",padding:16,borderRadius:9,border:"1px solid #203b52",background:m.read_at?"#0d1b29":"#10253a",color:"#e6f1fa",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><strong>{m.subject||"(sem assunto)"}</strong><div style={{color:"#9db1c1",marginTop:5}}>{m.from_name||m.from_address||"—"} {m.from_address&&m.from_name?"<"+m.from_address+">":""}</div></div><span style={{fontSize:12,color:"#7890a4"}}>{new Date(m.created_at).toLocaleString("pt-BR")}</span></div><div style={{marginTop:7,color:"#7890a4",fontSize:12}}>{m.mailbox?.display_name||m.to_addresses?.join(", ")||"HSI-DOTH-PG"} · {m.direction==="inbound"?"Recebido":"Enviado"}</div></button>)}{!messages.length&&!busy&&<div style={{padding:35,textAlign:"center",border:"1px dashed #31506b",color:"#91a5b5"}}>Nenhuma mensagem nesta pasta.</div>}</div></section></div></div>
 {selected&&<div onClick={()=>setSelected(null)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.72)",display:"grid",placeItems:"center",padding:20,zIndex:90}}><div onClick={e=>e.stopPropagation()} style={{background:"#0d1b29",border:"1px solid #31506b",borderRadius:12,maxWidth:900,width:"100%",maxHeight:"90vh",overflow:"auto",padding:28}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><div style={{color:"#82c8f7",fontSize:12,fontWeight:800}}>MENSAGEM</div><h2 style={{margin:"7px 0"}}>{selected.subject||"(sem assunto)"}</h2></div><button onClick={()=>setSelected(null)} style={btn}>Fechar</button></div><p><strong>De:</strong> {selected.from_name?selected.from_name+" <"+selected.from_address+">":selected.from_address||"—"}</p><p><strong>Para:</strong> {(selected.to_addresses||[]).join(", ")||"—"}</p>{selected.cc_addresses?.length>0&&<p><strong>Cc:</strong> {selected.cc_addresses.join(", ")}</p>}<hr style={{borderColor:"#203b52",margin:"18px 0"}}/><div style={{whiteSpace:"pre-wrap",lineHeight:1.7}}>{selected.text_body||"Sem texto disponível."}</div>{selected.attachments?.length>0&&<div style={{marginTop:22,paddingTop:15,borderTop:"1px solid #203b52"}}><strong>📎 Anexos</strong>{selected.attachments.map((a,i)=><div key={a.id||i} style={{padding:9,border:"1px solid #203b52",borderRadius:6,marginTop:6}}>{a.filename||a.name||"Anexo "+(i+1)}</div>)}</div>}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:22}}>{selected.direction==="inbound"&&<button onClick={()=>setCompose(selected)} style={primary}>↩ Responder</button>}<button onClick={()=>setCompose({...selected,forward:true})} style={btn}>↗ Encaminhar</button>{selected.folder==="inbox"&&<button onClick={()=>status(selected.id,"archive")} style={btn}>🗄 Arquivar</button>}{selected.folder!=="trash"&&<button onClick={()=>remove(selected.id)} style={{...btn,borderColor:"#754848",background:"#24171b",color:"#ffb4b4"}}>🗑 Lixeira</button>}{selected.folder==="trash"&&<button onClick={()=>status(selected.id,"inbox")} style={btn}>↩ Restaurar</button>}</div></div></div>}
 {compose&&<Composer mailboxes={mailboxes} selected={compose?.id?compose:null} onClose={()=>setCompose(null)} onSent={()=>{setCompose(null);setSelected(null);load()}}/>}
 </main>;
}