import React, { useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { cancelCertificate, getSession, issueCertificate, listCertificates, signIn, signOut, signUp } from "../lib/certificatesApi";
import "./EmissorCertificados.css";

const KEY_COURSE = "enat_certificate_cloud_course_v1";
const KEY_BRAND = "enat_certificate_brand_v1";
const DEFAULT_COURSE = { id:"enat-120", name:"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito", nature:"Curso Livre de Formação e Aperfeiçoamento", modality:"Online", responsible:"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito", subjects:[
 {name:"Legislação e Normas de Trânsito",hours:20},{name:"Psicologia, Neurociência e Comportamento",hours:25},{name:"Direção Defensiva e Percepção de Risco",hours:20},{name:"Infrações e Responsabilidade",hours:15},{name:"Mecânica Básica",hours:10},{name:"Primeiros Socorros",hours:10},{name:"Meio Ambiente, Ética e Cidadania",hours:20}
]};

function digits(v){return String(v||"").replace(/\D/g,"")}
function maskCPF(v){const d=digits(v);return d.length===11?`***.***.***-${d.slice(-2)}`:"CPF não informado"}
function totalHours(c){return (c?.subjects||[]).reduce((s,x)=>s+(Number(x.hours)||0),0)}
function fmtDate(v){return v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—"}
function nextCode(certs){const year=new Date().getFullYear();const max=(certs||[]).filter(c=>String(c.code||"").startsWith(`ENAT-${year}-`)).reduce((m,c)=>Math.max(m,Number(String(c.code).split("-").pop())||0),0);return `ENAT-${year}-${String(max+1).padStart(6,"0")}`}
async function sha256(value){const data=new TextEncoder().encode(value);const hash=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function loadBrand(){try{return JSON.parse(localStorage.getItem(KEY_BRAND))||{enatLogo:"",neuroLogo:""}}catch{return {enatLogo:"",neuroLogo:""}}}

export function EmissorCertificadosCloud(){
 const [session,setSession]=useState(null); const [authLoading,setAuthLoading]=useState(true); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [authMode,setAuthMode]=useState("login");
 const [course,setCourse]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY_COURSE))||DEFAULT_COURSE}catch{return DEFAULT_COURSE}});
 const [brand]=useState(loadBrand); const [certs,setCerts]=useState([]); const [name,setName]=useState(""); const [cpf,setCpf]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [tab,setTab]=useState("emitir");
 const total=useMemo(()=>totalHours(course),[course]);
 useEffect(()=>{getSession().then(({data})=>setSession(data.session)).catch(e=>setMessage(e.message)).finally(()=>setAuthLoading(false))},[]);
 useEffect(()=>{if(session) refresh()},[session]);
 async function refresh(){try{const data=await listCertificates();setCerts(data.certificates||[])}catch(e){setMessage(e.message)}}
 async function auth(){setBusy(true);setMessage("");try{const result=authMode==="login"?await signIn(email,password):await signUp(email,password);if(result.error)throw result.error;if(authMode==="signup")setMessage("Acesso criado. Se a confirmação de e-mail estiver habilitada, confirme o e-mail e depois entre no emissor.");else setSession(result.data.session)}catch(e){setMessage(e.message||"Não foi possível autenticar.")}finally{setBusy(false)}}
 async function logout(){await signOut();setSession(null);setCerts([])}
 function saveCourse(){localStorage.setItem(KEY_COURSE,JSON.stringify(course));setMessage("Configuração do curso salva neste dispositivo.")}
 async function generatePDF(c){const doc=new jsPDF({unit:"mm",format:"a4"}),w=210,h=297;doc.setFillColor(248,250,252);doc.rect(0,0,w,h,"F");doc.setDrawColor(11,45,75);doc.setLineWidth(1.2);doc.rect(7,7,w-14,h-14);doc.setDrawColor(194,145,35);doc.setLineWidth(.35);doc.rect(10,10,w-20,h-20);
  if(brand.enatLogo){try{doc.addImage(brand.enatLogo,"PNG",165,14,28,28,undefined,"FAST")}catch{}}
  if(brand.neuroLogo){try{if(doc.setGState&&doc.GState)doc.setGState(new doc.GState({opacity:.075}));doc.addImage(brand.neuroLogo,"PNG",35,82,140,128,undefined,"FAST");if(doc.setGState&&doc.GState)doc.setGState(new doc.GState({opacity:1}))}catch{}}
  doc.setTextColor(8,38,67);doc.setFont("helvetica","bold");doc.setFontSize(20);doc.text("ENAT",18,24);doc.setFontSize(7);doc.text("ENSINO NEUROEDUCACIONAL APLICADO AO TRÂNSITO",18,31);doc.setDrawColor(198,148,38);doc.setLineWidth(.7);doc.line(18,35,192,35);
  doc.setTextColor(8,38,67);doc.setFontSize(26);doc.text("CERTIFICADO",w/2,55,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(70,80,90);doc.text("CERTIFICADO DE PARTICIPAÇÃO E CONCLUSÃO — CURSO LIVRE",w/2,64,{align:"center"});doc.setFontSize(11);doc.text("Certificamos que",w/2,78,{align:"center"});doc.setFont("helvetica","bold");doc.setFontSize(20);doc.setTextColor(15,35,55);doc.text(c.name,w/2,94,{align:"center",maxWidth:170});doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`CPF: ${maskCPF(c.cpf)}`,w/2,103,{align:"center"});doc.setFontSize(11);doc.text("concluiu o",w/2,116,{align:"center"});doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text(c.course_name,w/2,126,{align:"center",maxWidth:170});doc.setFont("helvetica","normal");doc.setFontSize(9.5);doc.text(c.course_nature,w/2,136,{align:"center"});doc.text(`Carga horária total: ${c.hours} horas  •  Modalidade: ${course.modality}`,w/2,143,{align:"center"});let y=157;doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(8,38,67);doc.text("CONTEÚDO PROGRAMÁTICO",18,y);y+=7;doc.setFont("helvetica","normal");doc.setFontSize(8);(c.subjects||[]).forEach((s,i)=>{doc.text(`${i+1}. ${s.name}`,20,y);doc.text(`${s.hours}h`,178,y,{align:"right"});y+=5.2});y=Math.max(y+5,231);doc.setFontSize(8.5);doc.text(`Concluído em ${fmtDate(c.completion_date)}`,18,y);doc.text(`Responsável: ${c.responsible}`,18,y+6);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text(`CERTIFICADO Nº ${c.code}`,18,y+14);const qr=await QRCode.toDataURL(`${window.location.origin}/validar/${c.code}`,{width:180,margin:1});doc.addImage(qr,"PNG",164,241,27,27);doc.setFont("helvetica","normal");doc.setFontSize(6.5);doc.text("Escaneie para verificar",177.5,272,{align:"center"});doc.setDrawColor(11,45,75);doc.setLineWidth(.35);doc.line(55,258,145,258);doc.setFontSize(7);doc.text("Responsável pela emissão",w/2,263,{align:"center"});doc.setFontSize(6.2);doc.setTextColor(80,90,100);doc.text("Curso livre de formação, capacitação, aperfeiçoamento ou atualização. Este certificado não corresponde a diploma de graduação",w/2,282,{align:"center"});doc.text("nem a certificado de pós-graduação lato sensu ou título acadêmico reconhecido pelo MEC.",w/2,287,{align:"center"});doc.save(`${c.code}-${c.name.replace(/[^a-z0-9]+/gi,"-")}.pdf`)}
 async function emit(){if(!name.trim()||digits(cpf).length!==11||total<=0){setMessage("Informe nome, CPF válido e curso com carga horária.");return}setBusy(true);setMessage("");try{const code=nextCode(certs);const c={code,name:name.trim(),cpf_hash:await sha256(digits(cpf)),course_name:course.name,course_nature:course.nature,hours:total,subjects:course.subjects,completion_date:date,responsible:course.responsible};const data=await issueCertificate(c);const issued={...data.certificate,name:c.name,cpf,course_name:c.course_name,course_nature:c.course_nature,hours:c.hours,subjects:c.subjects,completion_date:c.completion_date,responsible:c.responsible};setCerts(x=>[issued,...x]);await generatePDF(issued);setMessage(`Certificado ${issued.code} emitido e registrado na Central ENAT HSI.`);setName("");setCpf("");}catch(e){setMessage(e.message||"Falha ao emitir certificado.")}finally{setBusy(false)}}
 async function toggle(c){setBusy(true);try{const status=c.status==="valid"?"cancelled":"valid";await cancelCertificate(c.code,status);setMessage(`Certificado ${c.code}: ${status==="valid"?"revalidado":"cancelado"}.`);await refresh()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 if(authLoading)return <main className="cert-main"><section className="panel"><h1>Emissor ENAT HSI</h1><p>Verificando acesso administrativo…</p></section></main>;
 if(!session)return <main className="cert-main"><section className="panel" style={{maxWidth:520,margin:"50px auto"}}><span className="eyebrow">CENTRAL ENAT HSI</span><h1>Emissor de Certificados</h1><p>O banco centralizado exige autenticação para emissão, cancelamento e revalidação.</p><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode==="login"?"current-password":"new-password"}/></label>{message&&<div className="notice">{message}</div>}<button className="primary" disabled={busy} onClick={auth}>{busy?"Aguarde…":authMode==="login"?"Entrar no emissor":"Criar acesso"}</button><button onClick={()=>setAuthMode(x=>x==="login"?"signup":"login")} style={{marginTop:10}}>{authMode==="login"?"Primeiro acesso / criar conta":"Já tenho conta / entrar"}</button></section></main>;
 return <main className="cert-main"><div className="cert-title"><div><span className="eyebrow">CENTRAL ENAT HSI • EMISSOR CENTRALIZADO</span><h1>Emissor de Certificados</h1><p>Emissão registrada no banco central da ENAT, com QR Code público para validação.</p></div><div><b>{certs.length}</b><span> certificados</span><button onClick={logout}>Sair</button></div></div>{message&&<div className="notice">{message}</div>}<nav className="cert-tabs"><button className={tab==="emitir"?"active":""} onClick={()=>setTab("emitir")}>Emitir</button><button className={tab==="curso"?"active":""} onClick={()=>setTab("curso")}>Curso</button><button className={tab==="historico"?"active":""} onClick={()=>setTab("historico")}>Certificados</button></nav>
 {tab==="emitir"&&<section className="grid2"><div className="panel"><h2>Dados do aluno</h2><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} /></label><label>CPF<input value={cpf} onChange={e=>setCpf(e.target.value)} inputMode="numeric" /></label><label>Data de conclusão<input type="date" value={date} onChange={e=>setDate(e.target.value)} /></label><button className="primary" disabled={busy} onClick={emit}>{busy?"Processando…":"Emitir e gerar PDF"}</button></div><div className="panel preview">{brand.enatLogo&&<img className="preview-logo" src={brand.enatLogo} alt="Logo ENAT"/>}<span className="mini">PRÉVIA</span><h2>Certificado ENAT</h2><div className="preview-name">{name||"Nome do aluno"}</div><p>CPF: {cpf?maskCPF(cpf):"***.***.***-00"}</p><h3>{course.name}</h3><strong>{total} horas</strong><p>{course.nature} • {course.modality}</p></div></section>}
 {tab==="curso"&&<section className="panel"><div className="section-head"><div><h2>Curso</h2><p>A configuração é usada na próxima emissão.</p></div><div className="hours">{total}<small> horas</small></div></div><div className="formgrid"><label>Nome<input value={course.name} onChange={e=>setCourse({...course,name:e.target.value})}/></label><label>Natureza<select value={course.nature} onChange={e=>setCourse({...course,nature:e.target.value})}><option>Curso Livre de Formação e Aperfeiçoamento</option><option>Curso Livre de Capacitação</option><option>Curso Livre de Atualização</option><option>Curso Livre de Aperfeiçoamento</option><option>Curso Livre de Formação Profissional</option></select></label><label>Modalidade<select value={course.modality} onChange={e=>setCourse({...course,modality:e.target.value})}><option>Online</option><option>Presencial</option><option>Híbrido</option></select></label><label>Responsável<input value={course.responsible} onChange={e=>setCourse({...course,responsible:e.target.value})}/></label></div><h3 className="subheading">Conteúdo programático</h3>{course.subjects.map((s,i)=><div className="subject" key={i}><input value={s.name} onChange={e=>setCourse({...course,subjects:course.subjects.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><input type="number" min="0" value={s.hours} onChange={e=>setCourse({...course,subjects:course.subjects.map((x,j)=>j===i?{...x,hours:Number(e.target.value)}:x)})}/><span>h</span><button onClick={()=>setCourse({...course,subjects:course.subjects.filter((_,j)=>j!==i)})}>×</button></div>)}<div className="actions"><button onClick={()=>setCourse({...course,subjects:[...course.subjects,{name:"Nova matéria",hours:0}]})}>+ Adicionar matéria</button><button className="primary" onClick={saveCourse}>Salvar curso</button></div></section>}
 {tab==="historico"&&<section className="panel"><h2>Certificados registrados</h2>{certs.length===0?<p className="empty">Nenhum certificado registrado.</p>:<div className="cert-list">{certs.map(c=><div className="cert-row" key={c.code}><div><b>{c.student_name||c.name}</b><span>{c.code} • {c.hours}h • {c.status==="valid"?"VÁLIDO":"CANCELADO"}</span></div><div><button onClick={()=>generatePDF({...c,name:c.student_name||c.name,cpf:"",course_name:c.course_name,course_nature:c.course_nature,subjects:c.subjects||course.subjects})}>PDF</button><button onClick={()=>toggle(c)}>{c.status==="valid"?"Cancelar":"Revalidar"}</button></div></div>)}</div>}</section>}
 </main>;
}
