import React,{useEffect,useMemo,useState} from "react";
import {EmissorCertificadosFinal} from "./EmissorCertificadosFinal";
import {listCourses,listStudents} from "../lib/certificatesApi";
import "./EmissorCertificadosComBusca.css";

const COURSE_KEY="enat_certificate_course_v3";
const PREFILL_KEY="enat_emissor_student_prefill_v1";
const digits=v=>String(v||"").replace(/\D/g,"");
const normalizeCourse=c=>({...c,nature:c.nature||"Curso Livre de Formação e Capacitação",modality:c.modality||"Online",responsible:c.responsible||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",responsibleRole:c.responsible_role||c.responsibleRole||"Responsável Técnico",author:c.author||"Vilmar Becker",authorRole:c.author_role||c.authorRole||"Autor e Responsável pelo Curso",modules:(c.modules||[]).map(m=>({...m,lessons:(m.lessons||[]).map(l=>({...l,teacherId:l.teacherId||""}))}))});
function setInputValue(input,value){if(!input)return;const proto=input.tagName==="TEXTAREA"?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}))}
function findLabelInput(text){const labels=[...document.querySelectorAll("label")];const label=labels.find(x=>x.textContent?.toLowerCase().includes(text.toLowerCase()));return label?.querySelector("input")||null}
function applyStudent(s){if(!s)return;const p={name:String(s.name||s.full_name||"").toUpperCase(),cpf:digits(s.cpf),credential:s.credential||"",uf:s.uf||""};sessionStorage.setItem(PREFILL_KEY,JSON.stringify(p));const apply=()=>{setInputValue(document.getElementById("student-name"),p.name);setInputValue(document.getElementById("student-cpf"),p.cpf);setInputValue(findLabelInput("Credencial DETRAN/UF"),p.credential)};apply();setTimeout(apply,100);setTimeout(apply,400)}
export function EmissorCertificadosComBusca(){
 const [students,setStudents]=useState([]),[courses,setCourses]=useState([]),[studentQuery,setStudentQuery]=useState(""),[courseQuery,setCourseQuery]=useState(""),[selectedStudent,setSelectedStudent]=useState(null),[selectedCourse,setSelectedCourse]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const errs=[];const [sr,cr]=await Promise.allSettled([listStudents(),listCourses()]);if(sr.status==="fulfilled")setStudents(sr.value?.students||[]);else errs.push(`Alunos: ${sr.reason?.message||"falha ao carregar"}`);if(cr.status==="fulfilled")setCourses((cr.value?.courses||[]).filter(c=>c.active!==false));else errs.push(`Cursos: ${cr.reason?.message||"falha ao carregar"}`);if(errs.length)setError(errs.join(" • "));setLoading(false)};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const raw=sessionStorage.getItem(PREFILL_KEY);if(!raw)return;try{const p=JSON.parse(raw);const t=setTimeout(()=>applyStudent(p),250);sessionStorage.removeItem(PREFILL_KEY);return()=>clearTimeout(t)}catch{sessionStorage.removeItem(PREFILL_KEY)}},[]);
 const filteredStudents=useMemo(()=>{const q=studentQuery.trim().toLowerCase();if(!q)return students.slice(0,8);return students.filter(s=>[s.name,s.full_name,s.cpf,s.credential,s.uf,s.enat_courses?.name].some(v=>String(v||"").toLowerCase().includes(q))).slice(0,8)},[students,studentQuery]);
 const filteredCourses=useMemo(()=>{const q=courseQuery.trim().toLowerCase();if(!q)return courses.slice(0,8);return courses.filter(c=>[c.name,c.code,c.category].some(v=>String(v||"").toLowerCase().includes(q))).slice(0,8)},[courses,courseQuery]);
 const chooseStudent=s=>{setSelectedStudent(s);applyStudent(s);if(s.course_id){const c=courses.find(x=>x.id===s.course_id);if(c){setSelectedCourse(c);localStorage.setItem(COURSE_KEY,JSON.stringify(normalizeCourse(c)));window.location.reload()}}};
 const chooseCourse=c=>{setSelectedCourse(c);localStorage.setItem(COURSE_KEY,JSON.stringify(normalizeCourse(c)));if(selectedStudent)applyStudent(selectedStudent);window.location.reload()};
 return <><section className="emissor-search-panel"><div className="emissor-search-title"><div><span>SELEÇÃO AUTOMÁTICA</span><h2>Buscar aluno e curso cadastrados</h2><p>Selecione os registros do banco e o emissor preencherá os dados automaticamente.</p></div><button className="emissor-search-refresh" onClick={load} disabled={loading}>↻ Atualizar bancos</button></div>{error&&<div className="emissor-search-error">{error}</div>}<div className="emissor-search-grid"><div className="emissor-search-card"><label>Buscar aluno<input value={studentQuery} onChange={e=>setStudentQuery(e.target.value)} placeholder="Nome, CPF, credencial ou UF"/></label><div className="emissor-search-results">{loading?<span>Carregando alunos…</span>:filteredStudents.length?filteredStudents.map(s=><button type="button" key={s.id} className={selectedStudent?.id===s.id?"selected":""} onClick={()=>chooseStudent(s)}><strong>{String(s.name||s.full_name||"").toUpperCase()}</strong><span>{s.cpf}{s.enat_courses?.name?` • ${s.enat_courses.name}`:""}</span></button>):<span>Nenhum aluno encontrado.</span>}</div></div><div className="emissor-search-card"><label>Buscar curso<input value={courseQuery} onChange={e=>setCourseQuery(e.target.value)} placeholder="Nome ou código do curso"/></label><div className="emissor-search-results">{loading?<span>Carregando cursos…</span>:filteredCourses.length?filteredCourses.map(c=><button type="button" key={c.id} className={selectedCourse?.id===c.id?"selected":""} onClick={()=>chooseCourse(c)}><strong>{c.name}</strong><span>{c.code} • {c.hours||0} horas {c.published?"• Publicado":"• Rascunho"}</span></button>):<span>Nenhum curso encontrado.</span>}</div></div></div></section><EmissorCertificadosFinal/></>;
}
