import React,{useEffect,useMemo,useState} from "react";
import {EmissorCertificadosFinal} from "./EmissorCertificadosFinal";
import {listCourses,listStudents} from "../lib/certificatesApi";
import "./EmissorCertificadosComBusca.css";

const COURSE_KEY="enat_certificate_course_v3",PREFILL_KEY="enat_emissor_student_prefill_v2";
const digits=v=>String(v||"").replace(/\D/g,"");
const normalizeCourse=c=>({...c,nature:c.nature||"Curso Livre de Formação e Capacitação",modality:c.modality||"Online",responsible:c.responsible||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",responsibleRole:c.responsible_role||c.responsibleRole||"Responsável Técnico",author:c.author||"Vilmar Becker",authorRole:c.author_role||c.authorRole||"Autor e Responsável pelo Curso",modules:(c.modules||[]).map(m=>({...m,lessons:(m.lessons||[]).map(l=>({...l,teacherId:l.teacherId||""}))}))});
const setInputValue=(input,value)=>{if(!input)return;const proto=input.tagName==="TEXTAREA"?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,"value")?.set;setter?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}))};
const findCredentialInput=()=>[...document.querySelectorAll("label")].find(x=>x.textContent?.toLowerCase().includes("credencial detran/uf"))?.querySelector("input")||null;
const currentStudent=()=>({name:String(document.getElementById("student-name")?.value||"").toUpperCase(),cpf:digits(document.getElementById("student-cpf")?.value||""),credential:findCredentialInput()?.value||""});
const applyStudent=s=>{if(!s)return;const p={name:String(s.name||s.full_name||"").toUpperCase(),cpf:digits(s.cpf),credential:s.credential||""};sessionStorage.setItem(PREFILL_KEY,JSON.stringify(p));const apply=()=>{setInputValue(document.getElementById("student-name"),p.name);setInputValue(document.getElementById("student-cpf"),p.cpf);setInputValue(findCredentialInput(),p.credential)};apply();setTimeout(apply,80);setTimeout(apply,250)};

export function EmissorCertificadosComBusca(){
 const [students,setStudents]=useState([]),[courses,setCourses]=useState([]),[sq,setSq]=useState(""),[cq,setCq]=useState(""),[open,setOpen]=useState(null),[pos,setPos]=useState({student:null,course:null}),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const [sr,cr]=await Promise.allSettled([listStudents(),listCourses()]);if(sr.status==="fulfilled")setStudents(sr.value?.students||[]);else setError(`Alunos: ${sr.reason?.message||"falha ao carregar"}`);if(cr.status==="fulfilled")setCourses((cr.value?.courses||[]).filter(c=>c.active!==false));else setError(e=>e?`${e} • Cursos: ${cr.reason?.message||"falha ao carregar"}`:`Cursos: ${cr.reason?.message||"falha ao carregar"}`);setLoading(false)};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const raw=sessionStorage.getItem(PREFILL_KEY);if(!raw)return;try{const p=JSON.parse(raw);const t=setTimeout(()=>{setInputValue(document.getElementById("student-name"),p.name);setInputValue(document.getElementById("student-cpf"),p.cpf);setInputValue(findCredentialInput(),p.credential);sessionStorage.removeItem(PREFILL_KEY)},300);return()=>clearTimeout(t)}catch{sessionStorage.removeItem(PREFILL_KEY)}},[]);
 const filteredStudents=useMemo(()=>{const q=sq.trim().toLowerCase();return students.filter(s=>!q||[s.name,s.full_name,s.cpf,s.credential,s.uf,s.enat_courses?.name].some(v=>String(v||"").toLowerCase().includes(q))).slice(0,8)},[students,sq]);
 const filteredCourses=useMemo(()=>{const q=cq.trim().toLowerCase();return courses.filter(c=>!q||[c.name,c.code,c.category].some(v=>String(v||"").toLowerCase().includes(q))).slice(0,8)},[courses,cq]);
 const updatePos=()=>{const name=document.getElementById("student-name");const course=document.querySelector(".issuer-grid > article:first-child .summary");setPos({student:name?name.getBoundingClientRect():null,course:course?course.getBoundingClientRect():null})};
 useEffect(()=>{const id=setTimeout(updatePos,100);window.addEventListener("resize",updatePos);window.addEventListener("scroll",updatePos,true);return()=>{clearTimeout(id);window.removeEventListener("resize",updatePos);window.removeEventListener("scroll",updatePos,true)}},[loading]);
 useEffect(()=>{if(open)updatePos()},[open]);
 useEffect(()=>{const close=e=>{if(open&&!e.target.closest(".inline-search-popover")&&!e.target.closest(".inline-search-trigger"))setOpen(null)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[open]);
 const chooseStudent=s=>{applyStudent(s);setOpen(null);if(s.course_id){const c=courses.find(x=>x.id===s.course_id);if(c){localStorage.setItem(COURSE_KEY,JSON.stringify(normalizeCourse(c)));window.location.reload()}}};
 const chooseCourse=c=>{sessionStorage.setItem(PREFILL_KEY,JSON.stringify(currentStudent()));localStorage.setItem(COURSE_KEY,JSON.stringify(normalizeCourse(c)));setOpen(null);window.location.reload()};
 const studentPos=pos.student,coursePos=pos.course,pop=open==="student"?studentPos:open==="course"?coursePos:null;
 return <><button type="button" className="inline-search-trigger student" style={studentPos?{left:studentPos.right-39,top:studentPos.top+7}:undefined} onClick={()=>setOpen(open==="student"?null:"student")} aria-label="Buscar aluno">⌕</button><button type="button" className="inline-search-trigger course" style={coursePos?{left:coursePos.right-96,top:coursePos.top+8}:undefined} onClick={()=>setOpen(open==="course"?null:"course")} aria-label="Buscar curso">⌕ Curso</button>{open&&pop&&<div className="inline-search-popover" style={{left:pop.left,top:pop.bottom+6,width:Math.min(pop.width,430)}} onMouseDown={e=>e.stopPropagation()}>{open==="student"?<><div className="popover-title">Buscar aluno cadastrado</div><input autoFocus value={sq} onChange={e=>setSq(e.target.value)} placeholder="Nome, CPF, credencial ou UF"/>{loading?<div className="popover-empty">Carregando…</div>:filteredStudents.map(s=><button key={s.id} type="button" className="popover-result" onClick={()=>chooseStudent(s)}><strong>{String(s.name||s.full_name||"").toUpperCase()}</strong><span>{s.cpf}{s.enat_courses?.name?` • ${s.enat_courses.name}`:""}</span></button>)}{!loading&&!filteredStudents.length&&<div className="popover-empty">Nenhum aluno encontrado.</div>}</>:<><div className="popover-title">Selecionar curso cadastrado</div><input autoFocus value={cq} onChange={e=>setCq(e.target.value)} placeholder="Nome ou código do curso"/>{loading?<div className="popover-empty">Carregando…</div>:filteredCourses.map(c=><button key={c.id} type="button" className="popover-result" onClick={()=>chooseCourse(c)}><strong>{c.name}</strong><span>{c.code} • {c.hours||0} horas {c.published?"• Publicado":"• Rascunho"}</span></button>)}{!loading&&!filteredCourses.length&&<div className="popover-empty">Nenhum curso encontrado.</div>}</>}</div>}<EmissorCertificadosFinal/></>;
}
