import React, { useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { useParams } from "react-router-dom";
import "./EmissorCertificados.css";

const KEY_COURSES = "enat_certificate_courses_v1";
const KEY_CERTS = "enat_certificates_v1";
const KEY_BRAND = "enat_certificate_brand_v1";
const DEFAULT_COURSE = { id:"default-enat-120", name:"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito", description:"Formação em neuroeducação aplicada ao trânsito.", modality:"Online", nature:"Curso Livre de Formação e Aperfeiçoamento", start:"", end:"", responsible:"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito", subjects:[{name:"Legislação e Normas de Trânsito",hours:20},{name:"Psicologia, Neurociência e Comportamento",hours:25},{name:"Direção Defensiva e Percepção de Risco",hours:20},{name:"Infrações e Responsabilidade",hours:15},{name:"Mecânica Básica",hours:10},{name:"Primeiros Socorros",hours:10},{name:"Meio Ambiente, Ética e Cidadania",hours:20}] };
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function maskCPF(v){const d=String(v).replace(/\D/g,"").slice(0,11);return d.length===11?`***.***.***-${d.slice(-2)}`:d}
function digits(v){return String(v).replace(/\D/g,"")}
function totalHours(c){return c.subjects.reduce((s,x)=>s+(Number(x.hours)||0),0)}
function nextCode(cs){const y=new Date().getFullYear();const max=cs.filter(c=>c.code?.startsWith(`ENAT-${y}-`)).reduce((m,c)=>Math.max(m,Number(c.code.split("-").pop())||0),0);return `ENAT-${y}-${String(max+1).padStart(6,"0")}`}
function readImage(file,setter){if(!file)return;const r=new FileReader();r.onload=()=>setter(r.result);r.readAsDataURL(file)}
function fmtDate(v){return v?new Date(v+"T12:00:00").toLocaleDateString("pt-BR"):"—"}

export function EmissorCertificados(){
 const initial=load(KEY_COURSES,[DEFAULT_COURSE]); const [courses,setCourses]=useState(initial); const [certs,setCerts]=useState(()=>load(KEY_CERTS,[])); const [brand,setBrand]=useState(()=>load(KEY_BRAND,{enatLogo:"",neuroLogo:""})); const [course,setCourse]=useState(initial[0]); const [name,setName]=useState(""); const [cpf,setCpf]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [message,setMessage]=useState(""); const [tab,setTab]=useState("emitir"); const total=useMemo(()=>totalHours(course),[course]);
 const updateCourse=(f,v)=>setCourse(c=>({...c,[f]:v})); const addSubject=()=>setCourse(c=>({...c,subjects:[...c.subjects,{name:"Nova matéria",hours:0}]}));
 const updateSubject=(i,f,v)=>setCourse(c=>({...c,subjects:c.subjects.map((s,j)=>j===i?{...s,[f]:f==="hours"?Number(v):v}:s)}));
 const saveCourse=()=>{const item={...course,id:course.id||crypto.randomUUID()};const u=courses.some(c=>c.id===item.id)?courses.map(c=>c.id===item.id?item:c):[...courses,item];setCourses(u);setCourse(item);save(KEY_COURSES,u);setMessage("Curso salvo com sucesso.")};
 const saveBrand=()=>{save(KEY_BRAND,brand);setMessage("Identidade visual salva. Os logos serão usados nos próximos certificados.")};
 async function generatePDF(c){
  const doc=new jsPDF({unit:"mm",format:"a4"}),w=210,h=297;
  doc.setFillColor(248,250,252);doc.rect(0,0,w,h,"F");doc.setDrawColor(11,45,75);doc.setLineWidth(1.2);doc.rect(7,7,w-14,h-14);doc.setDrawColor(194,145,35);doc.setLineWidth(.35);doc.rect(10,10,w-20,h-20);
  if(brand.enatLogo){try{doc.addImage(brand.enatLogo,"PNG",165,14,28,28,undefined,"FAST")}catch{}}
  if(brand.neuroLogo){try{if(doc.setGState&&doc.GState)doc.setGState(new doc.GState({opacity:.075}));doc.addImage(brand.neuroLogo,"PNG",35,82,140,128,undefined,"FAST");if(doc.setGState&&doc.GState)doc.setGState(new doc.GState({opacity:1}));}catch{}}
  doc.setTextColor(8,38,67);doc.setFont("helvetica","bold");doc.setFontSize(20);doc.text("ENAT",18,24);doc.setFontSize(7);doc.text("ENSINO NEUROEDUCACIONAL APLICADO AO TRÂNSITO",18,31);doc.setDrawColor(198,148,38);doc.setLineWidth(.7);doc.line(18,35,192,35);
  doc.setTextColor(8,38,67);doc.setFontSize(26);doc.text("CERTIFICADO",w/2,55,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(10);doc.setTextColor(70,80,90);doc.text("CERTIFICADO DE PARTICIPAÇÃO E CONCLUSÃO — CURSO LIVRE",w/2,64,{align:"center"});
  doc.setFontSize(11);doc.text("Certificamos que",w/2,78,{align:"center"});doc.setFont("helvetica","bold");doc.setFontSize(20);doc.setTextColor(15,35,55);doc.text(c.name,w/2,94,{align:"center"});doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`CPF: ${maskCPF(c.cpf)}`,w/2,103,{align:"center"});
  doc.setFontSize(11);doc.text("concluiu o",w/2,116,{align:"center"});doc.setFont("helvetica","bold");doc.setFontSize(14);doc.text(c.course.name,w/2,126,{align:"center",maxWidth:170});doc.setFont("helvetica","normal");doc.setFontSize(9.5);doc.text(c.course.nature||"Curso Livre",w/2,136,{align:"center"});doc.text(`Carga horária total: ${c.hours} horas  •  Modalidade: ${c.course.modality||"—"}`,w/2,143,{align:"center"});
  let y=157;doc.setFont("helvetica","bold");doc.setFontSize(10);doc.setTextColor(8,38,67);doc.text("CONTEÚDO PROGRAMÁTICO",18,y);y+=7;doc.setFont("helvetica","normal");doc.setFontSize(8);c.course.subjects.forEach((s,i)=>{if(y>223){doc.addPage();y=24}doc.text(`${i+1}. ${s.name}`,20,y);doc.text(`${s.hours}h`,178,y,{align:"right"});y+=5.2});
  y=Math.max(y+5,231);doc.setFontSize(8.5);doc.text(`Concluído em ${fmtDate(c.completionDate)}`,18,y);doc.text(`Responsável: ${c.course.responsible||"ENAT"}`,18,y+6);doc.setFont("helvetica","bold");doc.setFontSize(9);doc.text(`CERTIFICADO Nº ${c.code}`,18,y+14);
  const qr=await QRCode.toDataURL(`${window.location.origin}/validar/${c.code}`,{width:180,margin:1});doc.addImage(qr,"PNG",164,241,27,27);doc.setFont("helvetica","normal");doc.setFontSize(6.5);doc.text("Escaneie para verificar",177.5,272,{align:"center"});
  doc.setDrawColor(11,45,75);doc.setLineWidth(.35);doc.line(55,258,145,258);doc.setFontSize(7);doc.text("Responsável pela emissão",w/2,263,{align:"center"});
  doc.setFontSize(6.2);doc.setTextColor(80,90,100);doc.text("Curso livre de formação, capacitação, aperfeiçoamento ou atualização. Este certificado não corresponde a diploma de graduação",w/2,282,{align:"center"});doc.text("nem a certificado de pós-graduação lato sensu ou título acadêmico reconhecido pelo MEC.",w/2,287,{align:"center"});
  doc.save(`${c.code}-${c.name.replace(/[^a-z0-9]+/gi,"-")}.pdf`)
 }
 async function emit(){if(!name.trim()||digits(cpf).length!==11||!course.name.trim()||total<=0){setMessage("Informe nome, CPF válido e curso com carga horária.");return}const c={code:nextCode(certs),name:name.trim(),cpf:digits(cpf),course,hours:total,completionDate:date,status:"valid",issuedAt:new Date().toISOString()};const u=[c,...certs];setCerts(u);save(KEY_CERTS,u);await generatePDF(c);setMessage(`Certificado ${c.code} emitido com sucesso.`);setName("");setCpf("")}
 const toggle=(code)=>{const u=certs.map(c=>c.code===code?{...c,status:c.status==="valid"?"cancelled":"valid"}:c);setCerts(u);save(KEY_CERTS,u)};
 return <div className="cert-shell"><header className="cert-header"><div><strong>ENAT</strong><span> Emissor de Certificados</span></div><div className="hsi-badge">ENAT • HSI</div></header><main className="cert-main"><div className="cert-title"><div><span className="eyebrow">CENTRAL ENAT HSI</span><h1>Emissor de Certificados</h1><p>Configure cursos e emita certificados com identidade visual ENAT.</p></div><div className="stats"><b>{certs.length}</b><span>certificados</span></div></div><nav className="cert-tabs"><button className={tab==="emitir"?"active":""} onClick={()=>setTab("emitir")}>Emitir</button><button className={tab==="curso"?"active":""} onClick={()=>setTab("curso")}>Configurar curso</button><button className={tab==="visual"?"active":""} onClick={()=>setTab("visual")}>Identidade visual</button><button className={tab==="historico"?"active":""} onClick={()=>setTab("historico")}>Certificados</button></nav>{message&&<div className="notice">{message}</div>}
 {tab==="emitir"&&<section className="grid2"><div className="panel"><h2>Dados do aluno</h2><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome do aluno"/></label><label>CPF<input value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="000.000.000-00" inputMode="numeric"/></label><label>Data de conclusão<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Curso<select value={course.id} onChange={e=>setCourse(courses.find(x=>x.id===e.target.value)||courses[0])}>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="primary" onClick={emit}>Gerar certificado PDF</button></div><div className="panel preview">{brand.enatLogo&&<img className="preview-logo" src={brand.enatLogo} alt="Logo ENAT"/>}<span className="mini">PRÉVIA</span><h2>Certificado ENAT</h2><div className="preview-name">{name||"Nome do aluno"}</div><p>CPF: {cpf?maskCPF(cpf):"***.***.***-00"}</p><h3>{course.name||"Curso"}</h3><strong>{total} horas</strong><p>{course.nature||"Curso Livre"} • {course.modality}</p></div></section>}
 {tab==="curso"&&<section className="panel"><div className="section-head"><div><h2>Configuração do curso</h2><p>A carga horária é calculada automaticamente.</p></div><div className="hours">{total} <small>horas</small></div></div><div className="formgrid"><label>Nome do curso<input value={course.name} onChange={e=>updateCourse("name",e.target.value)}/></label><label>Natureza da formação<select value={course.nature} onChange={e=>updateCourse("nature",e.target.value)}><option>Curso Livre de Formação e Aperfeiçoamento</option><option>Curso Livre de Capacitação</option><option>Curso Livre de Atualização</option><option>Curso Livre de Aperfeiçoamento</option><option>Curso Livre de Formação Profissional</option></select></label><label>Modalidade<select value={course.modality} onChange={e=>updateCourse("modality",e.target.value)}><option>Online</option><option>Presencial</option><option>Híbrido</option></select></label><label>Responsável<input value={course.responsible} onChange={e=>updateCourse("responsible",e.target.value)}/></label><label>Início<input type="date" value={course.start} onChange={e=>updateCourse("start",e.target.value)}/></label><label>Término<input type="date" value={course.end} onChange={e=>updateCourse("end",e.target.value)}/></label><label>Descrição<input value={course.description} onChange={e=>updateCourse("description",e.target.value)}/></label></div><h3 className="subheading">Matérias</h3>{course.subjects.map((s,i)=><div className="subject" key={i}><input value={s.name} onChange={e=>updateSubject(i,"name",e.target.value)}/><input type="number" min="0" value={s.hours} onChange={e=>updateSubject(i,"hours",e.target.value)}/><span>h</span><button onClick={()=>setCourse(c=>({...c,subjects:c.subjects.filter((_,j)=>j!==i)}))}>×</button></div>)}<div className="actions"><button onClick={addSubject}>+ Adicionar matéria</button><button className="primary" onClick={saveCourse}>Salvar curso</button></div></section>}
 {tab==="visual"&&<section className="panel"><div className="section-head"><div><h2>Identidade visual do certificado</h2><p>Os arquivos enviados ficam salvos neste navegador e serão incorporados ao PDF.</p></div></div><div className="brand-grid"><div className="brand-box"><h3>Logo ENAT</h3>{brand.enatLogo?<img src={brand.enatLogo} alt="Logo ENAT"/>:<div className="brand-empty">Nenhum logo carregado</div>}<input type="file" accept="image/png,image/jpeg" onChange={e=>readImage(e.target.files?.[0],v=>setBrand(b=>({...b,enatLogo:v})))} /><small>Recomendado: PNG ou JPG com boa resolução.</small></div><div className="brand-box"><h3>Marca d’água — Neurociência Aplicada ao Trânsito</h3>{brand.neuroLogo?<img src={brand.neuroLogo} alt="Neurociência Aplicada ao Trânsito"/>:<div className="brand-empty">Nenhuma marca d’água carregada</div>}<input type="file" accept="image/png,image/jpeg" onChange={e=>readImage(e.target.files?.[0],v=>setBrand(b=>({...b,neuroLogo:v})))} /><small>O sistema aplica baixa opacidade automaticamente no centro do certificado.</small></div></div><div className="actions"><button onClick={()=>setBrand({enatLogo:"",neuroLogo:""})}>Remover logos</button><button className="primary" onClick={saveBrand}>Salvar identidade visual</button></div></section>}
 {tab==="historico"&&<section className="panel"><h2>Certificados emitidos</h2>{certs.length===0?<p className="empty">Nenhum certificado emitido ainda.</p>:<div className="cert-list">{certs.map(c=><div className="cert-row" key={c.code}><div><b>{c.name}</b><span>{c.code} • {c.hours}h • {c.course.nature||"Curso Livre"} • {c.status==="valid"?"Válido":"Cancelado"}</span></div><div><button onClick={()=>generatePDF(c)}>PDF</button><button onClick={()=>toggle(c.code)}>{c.status==="valid"?"Cancelar":"Revalidar"}</button></div></div>)}</div>}</section>}
 </main></div>
}

export function ValidarCertificado(){const {code}=useParams();const c=load(KEY_CERTS,[]).find(x=>x.code===code);return <div className="validate-page"><div className="validate-card"><div className="validate-brand">ENAT • HSI</div>{c?<><div className={c.status==="valid"?"valid":"cancelled"}>{c.status==="valid"?"CERTIFICADO VÁLIDO":"CERTIFICADO CANCELADO"}</div><h1>Autenticidade do certificado</h1><dl><dt>Certificado</dt><dd>{c.code}</dd><dt>Aluno</dt><dd>{c.name}</dd><dt>CPF</dt><dd>{maskCPF(c.cpf)}</dd><dt>Curso</dt><dd>{c.course.name}</dd><dt>Natureza</dt><dd>{c.course.nature||"Curso Livre"}</dd><dt>Carga horária</dt><dd>{c.hours} horas</dd><dt>Conclusão</dt><dd>{fmtDate(c.completionDate)}</dd></dl><p className="small">Esta página confirma os dados registrados no emissor ENAT.</p></>:<><div className="cancelled">NÃO ENCONTRADO</div><h1>Certificado não localizado</h1><p>Verifique o código informado.</p></>}</div></div>}
