import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../context/AuthContext";
import "./ENATTVNetworkAdmin.css";

const CATEGORIES = ["ENAT TV Ao Vivo", "ENAT Ciência", "ENAT Entrevistas", "ENAT Formação", "NeuroTrânsito", "ENAT Play"];
const STATUS = { draft: "Rascunho", scheduled: "Agendado", ready: "Pronto", live: "Ao vivo", ended: "Encerrado", cancelled: "Cancelado" };

function tokenValue() { const bytes = new Uint8Array(24); crypto.getRandomValues(bytes); return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join(""); }
async function sha256(value) { const data = new TextEncoder().encode(value); const digest = await crypto.subtle.digest("SHA-256", data); return Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, "0")).join(""); }

export function ENATTVNetworkAdmin() {
  const { session } = useAuth();
  const [programs, setPrograms] = useState([]); const [events, setEvents] = useState([]); const [guests, setGuests] = useState([]);
  const [tab, setTab] = useState("agenda"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [programForm, setProgramForm] = useState({ name: "", description: "", category: "ENAT TV Ao Vivo", host_name: "" });
  const [eventForm, setEventForm] = useState({ title: "", description: "", scheduled_start: "", scheduled_end: "", program_id: "", provider: "hybrid" });
  const [selectedEvent, setSelectedEvent] = useState(null); const [guestForm, setGuestForm] = useState({ display_name: "", email: "", role: "guest", expires_at: "" }); const [inviteLink, setInviteLink] = useState("");

  const load = async () => { if (!supabase) return; setMessage(""); const [p, e] = await Promise.all([supabase.from("enat_tv_programs").select("*").order("name"), supabase.from("enat_tv_events").select("*, enat_tv_programs(name)").order("scheduled_start")]); if (p.error || e.error) setMessage(p.error?.message || e.error?.message || "Não foi possível carregar a rede ENAT TV."); else { setPrograms(p.data || []); setEvents(e.data || []); } };
  useEffect(() => { load(); }, []);

  const upcoming = useMemo(() => events.filter((e) => e.status !== "cancelled").sort((a,b) => new Date(a.scheduled_start)-new Date(b.scheduled_start)), [events]);
  const saveProgram = async (ev) => { ev.preventDefault(); setBusy(true); setMessage(""); const { data, error } = await supabase.from("enat_tv_programs").insert({ ...programForm, created_by: session?.user?.id || null }).select().single(); if (error) setMessage(error.message); else { setPrograms((x) => [...x, data].sort((a,b)=>a.name.localeCompare(b.name))); setProgramForm({ name:"",description:"",category:"ENAT TV Ao Vivo",host_name:"" }); setMessage("Programa criado."); } setBusy(false); };
  const saveEvent = async (ev) => { ev.preventDefault(); if (!eventForm.title || !eventForm.scheduled_start) return; setBusy(true); setMessage(""); const payload = { ...eventForm, scheduled_start: new Date(eventForm.scheduled_start).toISOString(), scheduled_end: eventForm.scheduled_end ? new Date(eventForm.scheduled_end).toISOString() : null, program_id: eventForm.program_id || null, created_by: session?.user?.id || null }; const { data, error } = await supabase.from("enat_tv_events").insert(payload).select("*, enat_tv_programs(name)").single(); if (error) setMessage(error.message); else { setEvents((x)=>[...x,data].sort((a,b)=>new Date(a.scheduled_start)-new Date(b.scheduled_start))); setEventForm({ title:"",description:"",scheduled_start:"",scheduled_end:"",program_id:"",provider:"hybrid" }); setMessage("Transmissão agendada."); } setBusy(false); };
  const setEventStatus = async (eventId, status) => { setBusy(true); const patch = { status, updated_at: new Date().toISOString() }; if (status === "live") patch.started_at = new Date().toISOString(); if (status === "ended") patch.ended_at = new Date().toISOString(); const { error } = await supabase.from("enat_tv_events").update(patch).eq("id", eventId); if (error) setMessage(error.message); else { setEvents((x)=>x.map((e)=>e.id===eventId?{...e,...patch}:e)); setSelectedEvent((e)=>e?.id===eventId?{...e,...patch}:e); } setBusy(false); };
  const generateInvite = async (ev) => { if (!guestForm.display_name) { setMessage("Informe o nome do participante."); return; } setBusy(true); setInviteLink(""); const raw = tokenValue(); const hash = await sha256(raw); const expires = guestForm.expires_at ? new Date(guestForm.expires_at).toISOString() : new Date(new Date(ev.scheduled_start).getTime()+4*60*60*1000).toISOString(); const { error } = await supabase.from("enat_tv_guests").insert({ event_id: ev.id, display_name: guestForm.display_name, email: guestForm.email || null, role: guestForm.role, invite_token_hash: hash, expires_at: expires }); if (error) setMessage(error.message); else { const link = `${window.location.origin}/tv-estudio?token=${raw}`; setInviteLink(link); setGuests((x)=>[...x,{event_id:ev.id,display_name:guestForm.display_name,email:guestForm.email,role:guestForm.role,expires_at:expires}]); setGuestForm({ display_name:"",email:"",role:"guest",expires_at:"" }); setMessage("Convite criado. Copie o link e envie ao participante."); } setBusy(false); };
  const selectedGuests = useMemo(() => guests.filter((g)=>g.event_id===selectedEvent?.id), [guests, selectedEvent]);

  return <main className="tv-network-admin"><section className="network-shell"><header className="network-head"><div><span>ENAT TV · REDE</span><h1>Central de Transmissão</h1><p>Programação, estúdios virtuais, convidados e replays da rede ENAT TV.</p></div><div><Link to="/tv">📺 Abrir ENAT TV</Link><button onClick={load}>↻ Atualizar</button></div></header>
    {message && <div className="network-message">{message}</div>}
    <nav className="network-tabs"><button className={tab==="agenda"?"active":""} onClick={()=>setTab("agenda")}>📅 Programação</button><button className={tab==="programs"?"active":""} onClick={()=>setTab("programs")}>📺 Programas</button><button className={tab==="studio"?"active":""} onClick={()=>setTab("studio")}>🎥 Estúdios</button><button className={tab==="replay"?"active":""} onClick={()=>setTab("replay")}>📼 Replays</button></nav>
    {tab==="agenda" && <div className="network-grid"><section className="network-panel"><h2>Agendar transmissão</h2><form onSubmit={saveEvent}><input required placeholder="Nome do programa / transmissão" value={eventForm.title} onChange={(e)=>setEventForm({...eventForm,title:e.target.value})}/><select value={eventForm.program_id} onChange={(e)=>setEventForm({...eventForm,program_id:e.target.value})}><option value="">Sem programa fixo</option>{programs.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="datetime-local" required value={eventForm.scheduled_start} onChange={(e)=>setEventForm({...eventForm,scheduled_start:e.target.value})}/><input type="datetime-local" value={eventForm.scheduled_end} onChange={(e)=>setEventForm({...eventForm,scheduled_end:e.target.value})}/><select value={eventForm.provider} onChange={(e)=>setEventForm({...eventForm,provider:e.target.value})}><option value="hybrid">ENAT TV + YouTube</option><option value="youtube">YouTube</option><option value="webrtc">Estúdio WebRTC</option></select><textarea rows="4" placeholder="Descrição do programa" value={eventForm.description} onChange={(e)=>setEventForm({...eventForm,description:e.target.value})}/><button className="network-primary" disabled={busy}>📅 Agendar</button></form></section><section className="network-panel"><h2>Próximos programas</h2><div className="event-list">{upcoming.length?upcoming.map((e)=><button key={e.id} className="event-item" onClick={()=>{setSelectedEvent(e);setTab("studio")}}><div><b>{e.title}</b><span>{new Date(e.scheduled_start).toLocaleString("pt-BR")} · {e.enat_tv_programs?.name || "ENAT TV"}</span></div><em className={`event-status status-${e.status}`}>{STATUS[e.status]}</em></button>):<p>Nenhuma transmissão agendada.</p>}</div></section></div>}
    {tab==="programs" && <div className="network-grid"><section className="network-panel"><h2>Novo programa</h2><form onSubmit={saveProgram}><input required placeholder="Nome do programa" value={programForm.name} onChange={(e)=>setProgramForm({...programForm,name:e.target.value})}/><input placeholder="Apresentador" value={programForm.host_name} onChange={(e)=>setProgramForm({...programForm,host_name:e.target.value})}/><select value={programForm.category} onChange={(e)=>setProgramForm({...programForm,category:e.target.value})}>{CATEGORIES.map((c)=><option key={c}>{c}</option>)}</select><textarea rows="4" placeholder="Descrição" value={programForm.description} onChange={(e)=>setProgramForm({...programForm,description:e.target.value})}/><button className="network-primary" disabled={busy}>➕ Criar programa</button></form></section><section className="network-panel"><h2>Programas da rede</h2>{programs.map((p)=><article className="program-item" key={p.id}><b>{p.name}</b><span>{p.category} · {p.host_name || "Sem apresentador definido"}</span><p>{p.description || ""}</p></article>)}</section></div>}
    {tab==="studio" && <section className="network-panel"><h2>🎥 Estúdio e convidados</h2><select value={selectedEvent?.id || ""} onChange={(e)=>setSelectedEvent(events.find((x)=>x.id===e.target.value)||null)}><option value="">Selecione uma transmissão</option>{events.map((e)=><option key={e.id} value={e.id}>{new Date(e.scheduled_start).toLocaleString("pt-BR")} · {e.title}</option>)}</select>{selectedEvent && <div className="studio-admin"><div className="studio-event-card"><span>{STATUS[selectedEvent.status]}</span><h3>{selectedEvent.title}</h3><p>{new Date(selectedEvent.scheduled_start).toLocaleString("pt-BR")}</p><div className="studio-admin-actions"><button onClick={()=>setEventStatus(selectedEvent.id,"ready")} disabled={busy}>✓ Preparar</button><button onClick={()=>setEventStatus(selectedEvent.id,"live")} disabled={busy}>🔴 Entrar no ar</button><button onClick={()=>setEventStatus(selectedEvent.id,"ended")} disabled={busy}>■ Encerrar</button><Link to={`/tv?evento=${selectedEvent.id}`}>Ver página pública</Link></div></div><div className="invite-panel"><h3>Convidar apresentador / participante</h3><input placeholder="Nome" value={guestForm.display_name} onChange={(e)=>setGuestForm({...guestForm,display_name:e.target.value})}/><input placeholder="E-mail (opcional)" value={guestForm.email} onChange={(e)=>setGuestForm({...guestForm,email:e.target.value})}/><select value={guestForm.role} onChange={(e)=>setGuestForm({...guestForm,role:e.target.value})}><option value="host">Apresentador</option><option value="guest">Convidado</option><option value="producer">Produtor</option></select><button className="network-primary" onClick={()=>generateInvite(selectedEvent)} disabled={busy}>🔗 Gerar acesso ao estúdio</button>{inviteLink && <div className="invite-result"><b>Link do estúdio</b><input readOnly value={inviteLink}/><button onClick={()=>navigator.clipboard?.writeText(inviteLink)}>📋 Copiar link</button></div>}</div></div>}</section>}
    {tab==="replay" && <section className="network-panel"><h2>📼 Replays</h2><p>Após o encerramento, o administrador poderá associar o replay do provedor e publicá-lo no ENAT Play. A gravação não precisa ser armazenada no servidor do HSI.</p><div className="replay-list">{events.filter((e)=>e.status==="ended").map((e)=><article key={e.id}><b>{e.title}</b><span>{e.youtube_video_id?`YouTube: ${e.youtube_video_id}`:"Replay ainda não associado"}</span><button onClick={()=>setMessage("Próxima etapa: associar o replay e publicar no ENAT Play.")}>📼 Gerenciar replay</button></article>)}</div></section>}
  </section></main>;
}
