import React, { useEffect, useMemo, useState } from "react";
import { getNeuroDriveAdminSummary } from "../lib/neurodriveApi";
const cardStyle={background:"#0c1b29",border:"1px solid rgba(99,202,255,.18)",borderRadius:16,padding:20};
const muted={color:"#8fa8ba",fontSize:13};
const inputStyle={width:"100%",boxSizing:"border-box",minHeight:42,padding:"9px 11px",borderRadius:9,border:"1px solid rgba(99,202,255,.2)",background:"#091824",color:"#eaf6ff",outline:"none"};
const metricGrid={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14};
const sectionTitle={margin:"6px 0 18px",fontSize:20};
const fmt=v=>Number(v||0).toLocaleString("pt-BR"); const date=v=>v?new Date(v).toLocaleString("pt-BR"):"—";
function FilterSelect({label,value,onChange,children,disabled=false}){return <label style={{display:"grid",gap:6}}><span style={{...muted,letterSpacing:".08em"}}>{label}</span><select value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} style={{...inputStyle,opacity:disabled?.55:1}}>{children}</select></label>}
function Bar({value,max=1}){return <div style={{height:7,background:"#132c3c",borderRadius:99,marginTop:5}}><div style={{height:"100%",width:`${Math.round((value/max)*100)}%`,background:"#63caff",borderRadius:99}}/></div>}
export function NeuroDriveAdmin(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [filters,setFilters]=useState({uf:"",municipality:"",period:"all",employment:"",teaching:"",activity:"all"});
 const load=async(next=filters)=>{setLoading(true);setError("");try{setData(await getNeuroDriveAdminSummary(next));}catch(e){setError(e?.message||"Não foi possível carregar o NeuroDrive.");}finally{setLoading(false)}};
 useEffect(()=>{load();},[]);
 const update=(key,value)=>{const next={...filters,[key]:value};if(key==="uf")next.municipality="";setFilters(next);load(next)};
 const locality=data?.instructor_intelligence?.locality_distribution||[]; const selectedState=locality.find(x=>x.uf===filters.uf); const municipalities=selectedState?.municipalities||[];
 const municipalityOptions=useMemo(()=>municipalities.map(x=>x.name),[municipalities]); const instructor=data?.instructor_intelligence;
 const maxUf=Math.max(1,...(data?.uf_distribution||[]).map(x=>x.assessments)); const maxInstructorUf=Math.max(1,...(instructor?.instructor_uf_distribution||[]).map(x=>x.instructors)); const maxCity=Math.max(1,...municipalities.map(x=>x.instructors));
 const hasFilters=Object.values(filters).some(v=>v&&v!=="all"); const clear=()=>{const f={uf:"",municipality:"",period:"all",employment:"",teaching:"",activity:"all"};setFilters(f);load(f)};
 const headline=filters.municipality?`${filters.municipality} · ${filters.uf}`:filters.uf?`Estado de ${filters.uf}`:"Brasil";
 return <main style={{minHeight:"100vh",background:"#07111b",color:"#eaf6ff",padding:"32px 24px",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
 <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:28}}><div><div style={{...muted,letterSpacing:".12em"}}>PORTAL ADMINISTRATIVO · ENAT HSI</div><h1 style={{margin:"8px 0",fontSize:32}}>NEURODRIVE INSTRUTOR ENAT-HSI</h1><p style={{...muted,maxWidth:800,fontSize:15,lineHeight:1.6}}>Inteligência territorial administrativa do NeuroDrive. Os indicadores são agregados e não exibem nomes, CPF, e-mail ou registros individuais.</p></div><button onClick={()=>load()} disabled={loading} style={{border:"1px solid rgba(99,202,255,.35)",background:"#0e2535",color:"#bfeaff",borderRadius:10,padding:"11px 16px",cursor:"pointer"}}>{loading?"Atualizando…":"↻ Atualizar"}</button></header>
 {error&&<div style={{...cardStyle,borderColor:"rgba(255,100,100,.35)",marginBottom:20}}>Falha na integração: {error}</div>}{loading&&!data&&<div style={cardStyle}>Carregando inteligência territorial…</div>}
 {data&&<>
 <section style={{...cardStyle,marginBottom:18}}><div style={muted}>INTELIGÊNCIA TERRITORIAL · FILTROS</div><h2 style={sectionTitle}>Brasil → UF → Município</h2><p style={{...muted,marginTop:-8,marginBottom:18}}>Selecione uma UF para restringir os municípios. Use a busca para localizar uma cidade e os demais filtros para aprofundar a leitura.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,alignItems:"end"}}>
 <FilterSelect label="ESTADO (UF)" value={filters.uf} onChange={v=>update("uf",v)}><option value="">Todos os estados</option>{locality.map(x=><option key={x.uf} value={x.uf}>{x.uf} · {fmt(x.instructors)}</option>)}</FilterSelect>
 <label style={{display:"grid",gap:6}}><span style={{...muted,letterSpacing:".08em"}}>BUSCAR MUNICÍPIO</span><input disabled={!filters.uf} value={filters.municipality} onChange={e=>setFilters(f=>({...f,municipality:e.target.value}))} onKeyDown={e=>{if(e.key==="Enter")load({...filters,municipality:e.currentTarget.value})}} placeholder={filters.uf?"Digite parte do município…":"Selecione uma UF primeiro"} list="neurodrive-municipalities" style={{...inputStyle,opacity:filters.uf?1:.55}}/><datalist id="neurodrive-municipalities">{municipalityOptions.map(x=><option key={x} value={x}/>)}</datalist></label>
 <FilterSelect label="MUNICÍPIO" value={filters.municipality} onChange={v=>update("municipality",v)} disabled={!filters.uf}><option value="">Todos os municípios</option>{municipalities.map(x=><option key={x.name} value={x.name}>{x.name} · {fmt(x.instructors)}</option>)}</FilterSelect>
 <FilterSelect label="PERÍODO" value={filters.period} onChange={v=>update("period",v)}><option value="all">Todo o período</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="90d">Últimos 90 dias</option><option value="365d">Últimos 365 dias</option></FilterSelect>
 <FilterSelect label="ATIVIDADE" value={filters.activity} onChange={v=>update("activity",v)}><option value="all">Todos</option><option value="active">Com atividade</option><option value="inactive">Sem atividade</option></FilterSelect>
 <FilterSelect label="VÍNCULO" value={filters.employment} onChange={v=>update("employment",v)}><option value="">Todos</option>{(instructor?.employment_distribution||[]).map(x=><option key={x.name} value={x.name}>{x.name} · {fmt(x.count)}</option>)}</FilterSelect>
 <FilterSelect label="TIPO DE ENSINO" value={filters.teaching} onChange={v=>update("teaching",v)}><option value="">Todos</option>{(instructor?.teaching_distribution||[]).map(x=><option key={x.name} value={x.name}>{x.name} · {fmt(x.count)}</option>)}</FilterSelect>
 <button type="button" onClick={clear} disabled={!hasFilters} style={{...inputStyle,cursor:hasFilters?"pointer":"default",textAlign:"center",opacity:hasFilters?1:.55}}>Limpar filtros</button></div>
 <div style={{marginTop:16,padding:"13px 15px",borderRadius:10,background:"#091824",border:"1px solid rgba(99,202,255,.12)"}}><span style={muted}>LOCALIDADE SELECIONADA</span><strong style={{display:"block",marginTop:4,fontSize:18}}>{headline}</strong><span style={{...muted,display:"block",marginTop:4}}>{filters.uf?`${fmt(selectedState?.instructors||0)} instrutor(es) no recorte.`:"Visão nacional."}</span></div></section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14,marginBottom:18}}>{[["INSTRUTORES NO RECORTE",fmt(instructor?.registered),`${fmt(instructor?.total_registered_unfiltered)} no total`],["COM ATIVIDADE",fmt(instructor?.with_activity),"aulas registradas"],["SEM ATIVIDADE",fmt(instructor?.without_activity),"sem aula registrada"],["PERFIL COMPLETO",`${instructor?.profile_completion_rate??0}%`,`${fmt(instructor?.profile_complete)} perfis`],["AVALIAÇÕES HSI",fmt(data.totals.assessments),`média ${data.totals.average_score??"—"}`],["AULAS NO RECORTE",fmt(data.platform_intelligence?.lessons),"sem cancelamentos"]].map(([a,b,c])=><article key={a} style={cardStyle}><div style={muted}>{a}</div><strong style={{display:"block",fontSize:34,marginTop:8}}>{b}</strong><span style={muted}>{c}</span></article>)}</section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18,marginBottom:18}}><article style={cardStyle}><div style={muted}>MAPA TERRITORIAL · CADASTROS</div><h2 style={sectionTitle}>{filters.uf?`Municípios de ${filters.uf}`:"Instrutores por UF"}</h2>{filters.uf?municipalities.map(x=><div key={x.name} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.name}</span><b>{fmt(x.instructors)}</b></div><Bar value={x.instructors} max={maxCity}/></div>):(instructor?.instructor_uf_distribution||[]).map(x=><div key={x.uf} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.uf}</span><b>{fmt(x.instructors)}</b></div><Bar value={x.instructors} max={maxInstructorUf}/></div>)}{filters.uf&&!municipalities.length&&<span style={muted}>Nenhum município encontrado.</span>}<div style={{...muted,marginTop:14}}>{fmt(instructor?.states)} UFs · {fmt(instructor?.municipalities)} municípios no recorte</div></article>
 <article style={cardStyle}><div style={muted}>HSI · DISTRIBUIÇÃO TERRITORIAL</div><h2 style={sectionTitle}>Avaliações por UF</h2>{(data.uf_distribution||[]).map(x=><div key={x.uf} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.uf}</span><b>{fmt(x.assessments)}</b></div><Bar value={x.assessments} max={maxUf}/></div>)}{!data.uf_distribution?.length&&<span style={muted}>Nenhum dado HSI no recorte.</span>}</article></section>
 {filters.uf&&<section style={{...cardStyle,marginBottom:18}}><div style={muted}>LEITURA LOCAL</div><h2 style={sectionTitle}>Municípios de {filters.uf}</h2><div style={{...metricGrid,gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))"}}>{municipalities.slice(0,12).map(x=><button key={x.name} onClick={()=>update("municipality",x.name)} style={{...cardStyle,textAlign:"left",cursor:"pointer",color:"#eaf6ff"}}><div style={muted}>MUNICÍPIO</div><strong style={{display:"block",fontSize:18,marginTop:6}}>{x.name}</strong><span style={muted}>{fmt(x.instructors)} instrutor(es)</span></button>)}</div>{municipalities.length>12&&<div style={{...muted,marginTop:12}}>Exibindo 12 de {fmt(municipalities.length)} municípios; use a busca/seleção acima para os demais.</div>}</section>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18,marginBottom:18}}><article style={cardStyle}><div style={muted}>CLASSIFICAÇÃO DE RISCO</div><h2 style={sectionTitle}>Distribuição HSI</h2>{(data.risk_distribution||[]).map(x=><div key={x.risk} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.risk}</span><b>{fmt(x.count)}</b></div><Bar value={x.count} max={Math.max(1,...(data.risk_distribution||[]).map(r=>r.count))}/></div>)}</article><article style={cardStyle}><div style={muted}>PERFIL PROFISSIONAL</div><h2 style={sectionTitle}>Vínculo e tipo de ensino</h2>{(instructor?.employment_distribution||[]).slice(0,8).map(x=><div key={x.name} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.name}</span><b>{fmt(x.count)}</b></div><Bar value={x.count} max={Math.max(1,...(instructor?.employment_distribution||[]).map(r=>r.count))}/></div>)}</article></section>
 <section style={cardStyle}><div style={muted}>DADOS RECENTES · NÃO IDENTIFICÁVEIS</div><h2 style={{margin:"6px 0 16px"}}>Atividade NeuroDrive</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Data","UF","Município","Faixa etária","Categoria","Instrumento","Score","Risco"].map(h=><th key={h} style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.1)",color:"#8fa8ba"}}>{h}</th>)}</tr></thead><tbody>{(data.recent||[]).map((x,i)=><tr key={`${x.observed_at}-${i}`}>{[date(x.observed_at),x.uf||"—",x.municipality||"—",x.age_band||"—",x.cnh_category||"—",`${x.instrument||"HSI-DOTH-P"}${x.instrument_version?` v${x.instrument_version}`:""}`,x.total_score??"—",x.risk_class||"—"].map((v,j)=><td key={j} style={{padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.06)"}}>{v}</td>)}</tr>)}</tbody></table></div>{!data.recent?.length&&<p style={muted}>Nenhum dado no recorte.</p>}<div style={{...muted,marginTop:14}}>Última leitura: {date(data.generated_at)}</div></section>
 </>}</div></main>;
}
