import React,{useEffect,useMemo,useState}from"react";
import{getNeuroDriveAdminSummary}from"../lib/neurodriveApi";
const card={background:"#0c1b29",border:"1px solid rgba(99,202,255,.18)",borderRadius:16,padding:20};const muted={color:"#8fa8ba",fontSize:13};const input={width:"100%",boxSizing:"border-box",minHeight:42,padding:"9px 11px",borderRadius:9,border:"1px solid rgba(99,202,255,.2)",background:"#091824",color:"#eaf6ff",outline:"none"};const fmt=v=>Number(v||0).toLocaleString("pt-BR");const date=v=>v?new Date(v).toLocaleString("pt-BR"):"—";
function Select({label,value,onChange,children,disabled=false}){return <label style={{display:"grid",gap:6}}><span style={{...muted,letterSpacing:".08em"}}>{label}</span><select value={value}disabled={disabled}onChange={e=>onChange(e.target.value)}style={{...input,opacity:disabled?.55:1}}>{children}</select></label>}
function Bar({value,max=1}){return <div style={{height:7,background:"#132c3c",borderRadius:99,marginTop:5}}><div style={{height:"100%",width:`${Math.min(100,Math.round(value/max*100))}%`,background:"#63caff",borderRadius:99}}/></div>}
function Metric({title,value,note}){return <article style={card}><div style={muted}>{title}</div><strong style={{display:"block",fontSize:32,marginTop:8}}>{value}</strong><span style={muted}>{note}</span></article>}
export function NeuroDriveAdmin(){const[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const[filters,setFilters]=useState({uf:"",municipality:"",period:"all",employment:"",teaching:"",activity:"all"});const load=async(next=filters)=>{setLoading(true);setError("");try{setData(await getNeuroDriveAdminSummary(next))}catch(e){setError(e?.message||"Não foi possível carregar o NeuroDrive.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);const update=(key,value)=>{const next={...filters,[key]:value};if(key==="uf")next.municipality="";setFilters(next);load(next)};const clear=()=>{const f={uf:"",municipality:"",period:"all",employment:"",teaching:"",activity:"all"};setFilters(f);load(f)};const locality=data?.instructor_intelligence?.locality_distribution||[];const selected=locality.find(x=>x.uf===filters.uf);const municipalities=selected?.municipalities||[];const municipalityOptions=useMemo(()=>municipalities.map(x=>x.name),[municipalities]);const inst=data?.instructor_intelligence;const op=data?.operational||data?.platform_intelligence||{};const hasFilters=Object.values(filters).some(v=>v&&v!=="all");const headline=filters.municipality?`${filters.municipality} · ${filters.uf}`:filters.uf?`Estado de ${filters.uf}`:"Brasil";const maxUf=Math.max(1,...(inst?.instructor_uf_distribution||[]).map(x=>x.instructors));const maxCity=Math.max(1,...municipalities.map(x=>x.instructors));return <main style={{minHeight:"100vh",background:"#07111b",color:"#eaf6ff",padding:"32px 24px",fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1180,margin:"0 auto"}}>
<header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:28}}><div><div style={{...muted,letterSpacing:".12em"}}>PORTAL ADMINISTRATIVO · ENAT HSI</div><h1 style={{margin:"8px 0",fontSize:32}}>NEURODRIVE INSTRUTOR ENAT-HSI</h1><p style={{...muted,maxWidth:850,fontSize:15,lineHeight:1.6}}>Inteligência territorial e operacional agregada. A Central não exibe nomes, CPF, e-mail, placas, valores financeiros ou registros individuais.</p></div><button onClick={()=>load()}disabled={loading}style={{border:"1px solid rgba(99,202,255,.35)",background:"#0e2535",color:"#bfeaff",borderRadius:10,padding:"11px 16px",cursor:"pointer"}}>{loading?"Atualizando…":"↻ Atualizar"}</button></header>
{error&&<div style={{...card,borderColor:"rgba(255,100,100,.35)",marginBottom:20}}>Falha na integração: {error}</div>}{loading&&!data&&<div style={card}>Carregando inteligência territorial…</div>}
{data&&<>
<section style={{...card,marginBottom:18}}><div style={muted}>INTELIGÊNCIA TERRITORIAL · FILTROS</div><h2 style={{margin:"6px 0 10px",fontSize:20}}>Brasil → UF → Município</h2><p style={{...muted,marginTop:0,marginBottom:18}}>UF e município são dados obrigatórios para a inteligência territorial. Cadastros sem localização ficam pendentes e fora dos agrupamentos.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12,alignItems:"end"}}>
<Select label="ESTADO (UF)"value={filters.uf}onChange={v=>update("uf",v)}><option value="">Todos os estados</option>{locality.map(x=><option key={x.uf}value={x.uf}>{x.uf} · {fmt(x.instructors)}</option>)}</Select>
<label style={{display:"grid",gap:6}}><span style={{...muted,letterSpacing:".08em"}}>MUNICÍPIO</span><input disabled={!filters.uf}value={filters.municipality}onChange={e=>setFilters(f=>({...f,municipality:e.target.value}))}onKeyDown={e=>e.key==="Enter"&&load({...filters,municipality:e.currentTarget.value})}placeholder={filters.uf?"Digite ou selecione o município…":"Selecione uma UF primeiro"}list="neurodrive-municipalities"style={{...input,opacity:filters.uf?1:.55}}/><datalist id="neurodrive-municipalities">{municipalityOptions.map(x=><option key={x}value={x}/>)}</datalist></label>
<Select label="PERÍODO"value={filters.period}onChange={v=>update("period",v)}><option value="all">Todo o período</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="90d">Últimos 90 dias</option><option value="365d">Últimos 365 dias</option></Select>
<Select label="ATIVIDADE"value={filters.activity}onChange={v=>update("activity",v)}><option value="all">Todos</option><option value="active">Com atividade</option><option value="inactive">Sem atividade</option></Select>
<Select label="VÍNCULO"value={filters.employment}onChange={v=>update("employment",v)}><option value="">Todos</option>{(inst?.employment_distribution||[]).map(x=><option key={x.name}value={x.name}>{x.name} · {fmt(x.count)}</option>)}</Select>
<Select label="TIPO DE ENSINO"value={filters.teaching}onChange={v=>update("teaching",v)}><option value="">Todos</option>{(inst?.teaching_distribution||[]).map(x=><option key={x.name}value={x.name}>{x.name} · {fmt(x.count)}</option>)}</Select>
<button type="button"onClick={clear}disabled={!hasFilters}style={{...input,cursor:hasFilters?"pointer":"default",textAlign:"center",opacity:hasFilters?1:.55}}>Limpar filtros</button></div>
<div style={{marginTop:16,padding:"13px 15px",borderRadius:10,background:"#091824",border:"1px solid rgba(99,202,255,.12)"}}><span style={muted}>LOCALIDADE SELECIONADA</span><strong style={{display:"block",marginTop:4,fontSize:18}}>{headline}</strong><span style={{...muted,display:"block",marginTop:4}}>{filters.municipality?"Recorte municipal aplicado.":filters.uf?`${fmt(selected?.instructors||0)} instrutor(es) com localização válida no recorte.`:"Visão nacional."}</span></div></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14,marginBottom:18}}><Metric title="INSTRUTORES NO RECORTE"value={fmt(inst?.registered)}note={`${fmt(inst?.total_registered_unfiltered)} com localização válida`}/><Metric title="LOCALIZAÇÃO PENDENTE"value={fmt(inst?.pending_location)}note="fora da inteligência territorial"/><Metric title="COM ATIVIDADE"value={fmt(inst?.with_activity)}note="aulas registradas"/><Metric title="SEM ATIVIDADE"value={fmt(inst?.without_activity)}note="sem aula registrada"/><Metric title="PERFIL COMPLETO"value={`${inst?.profile_completion_rate??0}%`}note={`${fmt(inst?.profile_complete)} perfis`}/><Metric title="AVALIAÇÕES HSI"value={fmt(data.totals.assessments)}note={`média ${data.totals.average_score??"—"}`}/></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14,marginBottom:18}}><Metric title="ALUNOS"value={fmt(op.students)}note="registros agregados"/><Metric title="AULAS"value={fmt(op.lessons)}note="não canceladas no recorte"/><Metric title="RPA"value={fmt(op.rpa_reports)}note="relatórios agregados"/><Metric title="VEÍCULOS"value={fmt(op.vehicles)}note="cadastros agregados"/><Metric title="LICENÇAS"value={fmt(op.licenses)}note="registros agregados"/><Metric title="ASSINATURAS"value={fmt(op.subscriptions)}note="registros agregados"/><Metric title="LANÇAMENTOS FINANCEIROS"value={fmt(op.finance_entries)}note="quantidade, sem valores"/></section>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18,marginBottom:18}}><article style={card}><div style={muted}>MAPA TERRITORIAL · CADASTROS</div><h2 style={{margin:"6px 0 18px",fontSize:20}}>{filters.uf?`Municípios de ${filters.uf}`:"Instrutores por UF"}</h2>{filters.uf?municipalities.map(x=><div key={x.name}style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.name}</span><b>{fmt(x.instructors)}</b></div><Bar value={x.instructors}max={maxCity}/></div>):(inst?.instructor_uf_distribution||[]).map(x=><div key={x.uf}style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.uf}</span><b>{fmt(x.instructors)}</b></div><Bar value={x.instructors}max={maxUf}/></div>)}{filters.uf&&!municipalities.length&&<span style={muted}>Nenhum município encontrado.</span>}<div style={{...muted,marginTop:14}}>{fmt(inst?.states)} UFs · {fmt(inst?.municipalities)} municípios no recorte</div></article>
<article style={card}><div style={muted}>HSI · DISTRIBUIÇÃO TERRITORIAL</div><h2 style={{margin:"6px 0 18px",fontSize:20}}>Avaliações por UF</h2>{(data.uf_distribution||[]).map(x=><div key={x.uf}style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.uf}</span><b>{fmt(x.assessments)}</b></div><Bar value={x.assessments}max={Math.max(1,...(data.uf_distribution||[]).map(r=>r.assessments))}/></div>)}{!data.uf_distribution?.length&&<span style={muted}>Nenhum dado HSI disponível na camada integrada.</span>}</article></section>
{filters.uf&&<section style={{...card,marginBottom:18}}><div style={muted}>LEITURA LOCAL</div><h2 style={{margin:"6px 0 16px",fontSize:20}}>Municípios de {filters.uf}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:12}}>{municipalities.slice(0,12).map(x=><button key={x.name}onClick={()=>update("municipality",x.name)}style={{...card,textAlign:"left",cursor:"pointer",color:"#eaf6ff"}}><div style={muted}>MUNICÍPIO</div><strong style={{display:"block",fontSize:18,marginTop:6}}>{x.name}</strong><span style={muted}>{fmt(x.instructors)} instrutor(es)</span></button>)}</div>{municipalities.length>12&&<div style={{...muted,marginTop:12}}>Exibindo 12 de {fmt(municipalities.length)} municípios; use a busca acima para os demais.</div>}</section>}
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18,marginBottom:18}}><article style={card}><div style={muted}>CLASSIFICAÇÃO DE RISCO</div><h2 style={{margin:"6px 0 18px",fontSize:20}}>Distribuição HSI</h2>{(data.risk_distribution||[]).map(x=><div key={x.risk}style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.risk}</span><b>{fmt(x.count)}</b></div><Bar value={x.count}max={Math.max(1,...(data.risk_distribution||[]).map(r=>r.count))}/></div>)}{!data.risk_distribution?.length&&<span style={muted}>Nenhuma classificação HSI disponível.</span>}</article><article style={card}><div style={muted}>PERFIL PROFISSIONAL</div><h2 style={{margin:"6px 0 18px",fontSize:20}}>Vínculo e tipo de ensino</h2>{(inst?.employment_distribution||[]).map(x=><div key={x.name}style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><span>{x.name}</span><b>{fmt(x.count)}</b></div><Bar value={x.count}max={Math.max(1,...(inst?.employment_distribution||[]).map(r=>r.count))}/></div>)}{!inst?.employment_distribution?.length&&<span style={muted}>Nenhum perfil classificado.</span>}</article></section>
<section style={card}><div style={muted}>DADOS RECENTES · AGREGADOS</div><h2 style={{margin:"6px 0 16px"}}>Atividade HSI por período, UF e risco</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Data","UF","Risco","Quantidade"].map(h=><th key={h}style={{textAlign:"left",padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.1)",color:"#8fa8ba"}}>{h}</th>)}</tr></thead><tbody>{(data.recent||[]).map((x,i)=><tr key={`${x.date}-${x.uf}-${x.risk}-${i}`}>{[x.date,x.uf||"—",x.risk||"Não classificado",fmt(x.count)].map((v,j)=><td key={j}style={{padding:"10px 8px",borderBottom:"1px solid rgba(255,255,255,.06)"}}>{v}</td>)}</tr>)}</tbody></table></div>{!data.recent?.length&&<p style={muted}>Nenhum dado HSI agregado no recorte.</p>}<div style={{...muted,marginTop:14}}>Última leitura: {date(data.generated_at)} · PII excluída · registros individuais excluídos</div></section>
</>}</div></main>}
