import {useEffect,useState} from "react";
import {NavLink,useNavigate} from "react-router-dom";
import {BrandingENAT} from "../components/BrandingENAT";
import {SocialShareENAT} from "../components/SocialShareENAT";
import {supabase} from "../lib/supabaseClient";
import {DepoimentosPublicosENAT} from "./DepoimentosInstrutoresENAT";
import "./PortalPublicoENAT.css";

const inbox=import.meta.env.VITE_SUPABASE_URL?`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/enat-public-inbox`:"";
const fallbackMenu=[['inicio','Início'],['sobre','O ENAT'],['autor','Palavra do Autor'],['cursos','Cursos'],['artigos','Artigos & Notícias'],['depoimentos','Depoimentos'],['interesse','Quero participar'],['publicar','Publique no ENAT'],['contato','Contato']];
const fallback={hero:{title:"Ciência, educação e comportamento para um trânsito mais humano e seguro.",subtitle:"ENSINO NEUROEDUCACIONAL APLICADO AO TRÂNSITO",body:"O ENAT desenvolve formação, conhecimento, pesquisa e soluções educacionais voltadas à compreensão do fator humano no trânsito.",button_label:"Conheça os cursos",metadata:{secondary_button:"Tenho interesse"}},about:{title:"Ensino Neuroeducacional Aplicado ao Trânsito",subtitle:"O ENAT",body:"Uma proposta de educação e desenvolvimento humano aplicada ao contexto do trânsito, com atenção aos processos cognitivos, emocionais, comportamentais e sociais que influenciam decisões e atitudes."},ecosystem:{title:"Um ecossistema de conhecimento",subtitle:"CONHEÇA",body:"Conteúdo institucional, cursos, artigos, notícias, pesquisas e participação da comunidade."},approach:{title:"Uma abordagem centrada no ser humano",body:"O ENAT busca aproximar conhecimento científico e prática educacional, valorizando formação profissional, percepção de risco, decisões responsáveis e humanização."}};
function Form({kind,title,subtitle,children}){const [f,setF]=useState({consent:false}),[files,setFiles]=useState([]),[sent,setSent]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);const set=(k,v)=>setF(x=>({...x,[k]:v}));const submit=async e=>{e.preventDefault();setError("");setBusy(true);try{let r;if(files.length){const fd=new FormData;Object.entries({...f,kind}).forEach(([k,v])=>fd.append(k,String(v??"")));files.forEach(x=>fd.append("files",x,x.name));r=await fetch(inbox,{method:"POST",body:fd})}else r=await fetch(inbox,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,kind})});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||"Falha no envio");setSent(true)}catch(e){setError(e.message)}finally{setBusy(false)}};if(sent)return <div className="portal-success"><strong>Recebemos sua mensagem.</strong><p>Obrigado pela participação. Nossa equipe fará a análise e poderá entrar em contato.</p></div>;return <form className="portal-form" onSubmit={submit}><h3>{title}</h3><p className="muted">{subtitle}</p><div className="portal-grid">{children({f,set})}</div><label className="consent"><input type="checkbox" checked={!!f.consent} onChange={e=>set("consent",e.target.checked)} required/> Autorizo o ENAT a utilizar estes dados para responder à mensagem e, quando aplicável, publicar o material enviado.</label>{error&&<div className="portal-error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Enviando…":"Enviar"}</button></form>}
const Field=({label,value,onChange,type="text",required=false})=><label className="field"><span>{label}{required?" *":""}</span>{type==="textarea"?<textarea rows={7} value={value||""} onChange={e=>onChange(e.target.value)} required={required}/>:<input type={type} value={value||""} onChange={e=>onChange(e.target.value)} required={required}/>}</label>;
export function PortalPublicoENAT(){const nav=useNavigate(),[tab,setTab]=useState("inicio"),[content,setContent]=useState([]),[courses,setCourses]=useState([]),[editorial,setEditorial]=useState([]),[author,setAuthor]=useState(null);useEffect(()=>{(async()=>{const [p,c,e,a]=await Promise.all([supabase.from("enat_public_content").select("*").eq("published",true).order("section_key").order("sort_order"),supabase.from("enat_courses").select("id,name,nature,modality,hours,summary,category").eq("published",true).eq("active",true).order("created_at",{ascending:false}),supabase.from("enat_public_editorial").select("id,kind,title,summary,author_name,category,image_url,published_at").eq("published",true).order("published_at",{ascending:false}),supabase.from("enat_public_content").select("*").eq("section_key","about.author").eq("published",true).maybeSingle()]);setContent(p.data||[]);setCourses(c.data||[]);setEditorial(e.data||[]);setAuthor(a.data||null)})()},[]);const get=(k,fb)=>content.find(x=>x.section_key===k)||fb;const menuRows=content.filter(x=>x.section_key==="menu.item");const menu=menuRows.length?menuRows.map(x=>[x.metadata?.id||x.id,x.title]):fallbackMenu;const hero=get("home.hero",fallback.hero),about=get("about.intro",fallback.about),ecosystem=get("home.ecosystem",fallback.ecosystem),approach=get("about.approach",fallback.approach),settings=get("site.settings",{metadata:{}});const values=content.filter(x=>x.section_key==="about.value");const features=content.filter(x=>x.section_key==="home.feature");const a=author?.metadata||{};const publicBase=window.location.origin;return <div className="portal-publico"><header className="portal-header"><NavLink to="/portal" className="portal-brand"><BrandingENAT variant="header"/></NavLink><nav>{menu.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><button className="admin-entry" onClick={()=>nav("/login")}>🔐 Portal Administrativo</button></header><main>
{tab==="inicio"&&<><section className="hero"><div className="hero-copy"><span className="eyebrow">{hero.subtitle}</span><h1>{hero.title}</h1><p>{hero.body}</p><div className="actions"><button className="primary" onClick={()=>setTab("cursos")}>{hero.button_label||"Conheça os cursos"}</button><button className="secondary" onClick={()=>setTab("interesse")}>{hero.metadata?.secondary_button||"Tenho interesse"}</button></div></div><div className="hero-card"><div className="brain">🧠</div><h2>ENAT HSI</h2><p>Neuroeducação, segurança viária, comportamento humano e formação profissional.</p></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">{ecosystem.subtitle}</span><h2>{ecosystem.title}</h2></div><p>{ecosystem.body}</p></div><div className="cards four">{(features.length?features:[{title:"Neuroeducação",body:"Aprendizagem, cognição e comportamento."},{title:"Segurança viária",body:"Foco no fator humano e na prevenção."},{title:"Pesquisa",body:"Conhecimento aplicado ao trânsito."},{title:"Formação",body:"Cursos e experiências para profissionais."}]).map((x,i)=><article key={x.id||i}><b>{x.title}</b><p>{x.body}</p></article>)}</div></section></>}
{tab==="sobre"&&<section className="section prose"><span className="eyebrow">{about.subtitle}</span><h1>{about.title}</h1><p>{about.body}</p><div className="cards three">{(values.length?values:[{title:"Missão",body:"Promover conhecimento, formação e inovação para compreender e transformar o comportamento humano no trânsito."},{title:"Visão",body:"Ser referência em neuroeducação aplicada ao trânsito."},{title:"Valores",body:"Vida, ética, responsabilidade, ciência, respeito, humanização e inovação."}]).map((x,i)=><article key={x.id||i}><h3>{x.title}</h3><p>{x.body}</p></article>)}</div><h2>{approach.title}</h2><p>{approach.body}</p></section>}
{tab==="autor"&&<section className="section prose"><span className="eyebrow">{author?.subtitle||"AUTORIA"}</span><h1>{author?.title||"Palavra do Autor"}</h1><div className="hero-card" style={{maxWidth:900,margin:"30px auto"}}>{a.photo_url&&<img src={a.photo_url} alt={a.name||"Autor"} style={{width:130,height:130,borderRadius:"50%",objectFit:"cover"}}/>}<h2>{a.name||"Vilmar Becker"}</h2><p><strong>{a.role||"Autor e idealizador do ENAT"}</strong></p><p style={{whiteSpace:"pre-wrap",lineHeight:1.8}}>{author?.body||""}</p><p><strong>{a.signature||a.name||"Vilmar Becker"}</strong></p><SocialShareENAT title={author?.title||"Palavra do Autor"} url={`${publicBase}/portal?secao=autor`}/></div></section>}
{tab==="cursos"&&<section className="section"><span className="eyebrow">FORMAÇÃO</span><h1>Cursos ENAT</h1>{courses.length?<div className="cards three">{courses.map(c=><article key={c.id}><span className="tag">{c.category||"ENAT"}</span><h3>{c.name}</h3><p>{c.summary||c.nature}</p><small>{c.hours?`${c.hours} horas · `:""}{c.modality}</small><button className="text-button" onClick={()=>setTab("interesse")}>Tenho interesse →</button></article>)}</div>:<div className="empty"><h3>Novas turmas em breve</h3><p>Cadastre seu interesse para receber informações.</p></div>}</section>}
{tab==="artigos"&&<section className="section"><span className="eyebrow">CONHECIMENTO ENAT</span><h1>Artigos & Notícias</h1>{editorial.length?<div className="cards two">{editorial.map(x=><article key={x.id}>{x.image_url&&<img src={x.image_url} alt=""/>}<span className="tag">{x.kind==="news"?"NOTÍCIA":"ARTIGO"}</span><h3>{x.title}</h3><p>{x.summary}</p><small>{x.author_name||"ENAT"}{x.category?` · ${x.category}`:""}</small><SocialShareENAT title={x.title} url={`${publicBase}/portal?conteudo=${encodeURIComponent(x.id)}`}/></article>)}</div>:<div className="empty"><h3>Nenhum conteúdo publicado ainda</h3><p>Novos artigos e notícias serão disponibilizados aqui.</p></div>}</section>}
{tab==="depoimentos"&&<DepoimentosPublicosENAT/>}
{tab==="interesse"&&<section className="section narrow"><span className="eyebrow">PARTICIPE</span><Form kind="interest" title="Quero participar do ENAT" subtitle="Cadastre seu interesse em cursos, palestras, workshops, pesquisas ou parcerias.">{({f,set})=><><Field label="Nome" value={f.name} onChange={v=>set("name",v)} required/><Field label="E-mail" type="email" value={f.email} onChange={v=>set("email",v)} required/><Field label="WhatsApp" value={f.phone} onChange={v=>set("phone",v)}/><Field label="Cidade" value={f.city} onChange={v=>set("city",v)}/><Field label="UF" value={f.state} onChange={v=>set("state",v)}/><Field label="Profissão" value={f.profession} onChange={v=>set("profession",v)}/><Field label="Mensagem" type="textarea" value={f.summary} onChange={v=>set("summary",v)}/></>}</Form></section>}
{tab==="publicar"&&<section className="section narrow"><span className="eyebrow">COMUNIDADE ENAT</span><Form kind="article_submission" title="Publique seu conhecimento no ENAT" subtitle="Envie artigo, pesquisa, ensaio ou relato para análise editorial.">{({f,set})=><><Field label="Nome" value={f.name} onChange={v=>set("name",v)} required/><Field label="E-mail" type="email" value={f.email} onChange={v=>set("email",v)} required/><Field label="Título" value={f.title} onChange={v=>set("title",v)} required/><Field label="Resumo" type="textarea" value={f.summary} onChange={v=>set("summary",v)}/><Field label="Conteúdo" type="textarea" value={f.content} onChange={v=>set("content",v)}/></>}</Form></section>}
{tab==="contato"&&<section className="section narrow"><span className="eyebrow">FALE CONOSCO</span><Form kind="contact" title="Entre em contato" subtitle="Informações, convites, parcerias, imprensa ou outras demandas institucionais.">{({f,set})=><><Field label="Nome" value={f.name} onChange={v=>set("name",v)} required/><Field label="E-mail" type="email" value={f.email} onChange={v=>set("email",v)} required/><Field label="Assunto" value={f.subject} onChange={v=>set("subject",v)} required/><Field label="Mensagem" type="textarea" value={f.message} onChange={v=>set("message",v)} required/></>}</Form></section>}
</main><footer className="portal-footer"><BrandingENAT variant="footer"/><span className="portal-footer-copy">ENAT — Ensino Neuroeducacional Aplicado ao Trânsito</span><div className="portal-socials">{settings.metadata?.instagram_url&&<a href={settings.metadata.instagram_url} target="_blank" rel="noreferrer noopener">Instagram</a>}{settings.metadata?.linkedin_url&&<a href={settings.metadata.linkedin_url} target="_blank" rel="noreferrer noopener">LinkedIn</a>}{settings.metadata?.youtube_url&&<a href={settings.metadata.youtube_url} target="_blank" rel="noreferrer noopener">YouTube</a>}</div></footer></div>}
