import { useEffect, useState } from "react";
import { NavLink, useNavigate } from "react-router-dom";
import { BrandingENAT } from "../components/BrandingENAT";
import { supabase } from "../lib/supabaseClient";
import "./PortalPublicoENAT.css";

const functionsUrl = import.meta.env.VITE_SUPABASE_URL ? `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/enat-public-inbox` : "";
const MAX_FILES = 5;
const MAX_FILE_SIZE = 15 * 1024 * 1024;
const ALLOWED_EXT = ["pdf","doc","docx","odt","txt","rtf","md","jpg","jpeg","png"];

function PublicForm({ kind, title, subtitle, children, initial = {} }) {
  const [form,setForm]=useState(initial); const [files,setFiles]=useState([]); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false); const [error,setError]=useState("");
  const set=(key,value)=>setForm(v=>({...v,[key]:value}));
  const handleFiles=(list)=>{setError("");const selected=Array.from(list||[]);if(selected.length>MAX_FILES){setError(`É permitido anexar no máximo ${MAX_FILES} arquivos.`);return;}const invalid=selected.find(f=>{const ext=(f.name.split(".").pop()||"").toLowerCase();return !ALLOWED_EXT.includes(ext)||f.size>MAX_FILE_SIZE;});if(invalid){const ext=(invalid.name.split(".").pop()||"").toLowerCase();setError(!ALLOWED_EXT.includes(ext)?`Formato não permitido: ${invalid.name}.`:`O arquivo ${invalid.name} excede o limite de 15 MB.`);return;}setFiles(selected);};
  const removeFile=(index)=>setFiles(v=>v.filter((_,i)=>i!==index));
  const submit=async e=>{e.preventDefault();setError("");setBusy(true);try{let r;if(files.length){const fd=new FormData();Object.entries({...form,kind}).forEach(([k,v])=>fd.append(k,typeof v==="boolean"?String(v):String(v??"")));files.forEach(file=>fd.append("files",file,file.name));r=await fetch(functionsUrl,{method:"POST",body:fd});}else{r=await fetch(functionsUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,kind})});}const data=await r.json();if(!r.ok||data.error)throw new Error(data.error||"Não foi possível enviar.");setSent(true);}catch(err){setError(err.message||"Erro no envio.");}finally{setBusy(false)}};
  if(sent)return <div className="portal-success"><strong>Recebemos sua mensagem.</strong><p>Obrigado pelo interesse no ENAT. Nossa equipe poderá entrar em contato pelos dados informados.</p><button onClick={()=>{setSent(false);setForm(initial);setFiles([])}}>Enviar outra</button></div>;
  return <form className="portal-form" onSubmit={submit}><div><h3>{title}</h3><p className="muted">{subtitle}</p></div><div className="portal-grid">{children({form,set,files,setFiles,removeFile})}</div><input tabIndex="-1" autoComplete="off" className="hp" aria-hidden="true" value={form.website||""} onChange={e=>set("website",e.target.value)}/><label className="consent"><input type="checkbox" checked={!!form.consent} onChange={e=>set("consent",e.target.checked)} required/> Autorizo o ENAT a utilizar estes dados para responder ao contato e, quando aplicável, enviar informações relacionadas ao interesse manifestado.</label>{error&&<div className="portal-error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Enviando…":"Enviar"}</button></form>;
}

const Field=({label,name,type="text",value,onChange,required=false,placeholder})=><label className="field"><span>{label}{required?" *":""}</span>{type==="textarea"?<textarea value={value||""} onChange={e=>onChange(e.target.value)} required={required} placeholder={placeholder||""}/>:<input type={type} value={value||""} onChange={e=>onChange(e.target.value)} required={required} placeholder={placeholder||""}/>}</label>;

function AttachmentField({files,setFiles,removeFile}){return <div className="field" style={{gridColumn:"1 / -1"}}><span>Anexar documentos</span><input type="file" multiple accept={ALLOWED_EXT.map(x=>`.${x}`).join(",")} onChange={e=>setFiles(e.target.files)} /><small className="muted" style={{display:"block",marginTop:7}}>Até {MAX_FILES} arquivos, máximo de 15 MB por arquivo. Formatos: PDF, DOC, DOCX, ODT, TXT, RTF, MD, JPG e PNG.</small>{files.length>0&&<div style={{display:"grid",gap:6,marginTop:10}}>{files.map((f,i)=><div key={`${f.name}-${i}`} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,padding:"8px 10px",border:"1px solid rgba(130,200,247,.25)",borderRadius:6}}><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>📎 {f.name}</span><button type="button" onClick={()=>removeFile(i)} style={{background:"transparent",border:0,color:"#82c8f7",cursor:"pointer"}}>Remover</button></div>)}</div>}</div>}

export function PortalPublicoENAT(){
 const navigate=useNavigate(); const [tab,setTab]=useState("inicio"); const [courses,setCourses]=useState([]); const [editorial,setEditorial]=useState([]);
 useEffect(()=>{(async()=>{if(!supabase)return;const [{data:c},{data:e}]=await Promise.all([supabase.from("enat_courses").select("id,name,code,nature,modality,hours,summary,category,slug").eq("published",true).eq("active",true).order("created_at",{ascending:false}),supabase.from("enat_public_editorial").select("id,kind,title,slug,summary,author_name,category,image_url,published_at,featured").eq("published",true).order("published_at",{ascending:false})]);setCourses(c||[]);setEditorial(e||[]);})();},[]);
 const menu=[['inicio','Início'],['sobre','O ENAT'],['cursos','Cursos'],['artigos','Artigos & Notícias'],['interesse','Quero participar'],['publicar','Publique no ENAT'],['contato','Contato']];
 return <div className="portal-publico"><header className="portal-header"><NavLink to="/portal" className="portal-brand"><BrandingENAT variant="header"/></NavLink><nav>{menu.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><button className="admin-entry" onClick={()=>navigate("/login")}>🔐 Portal Administrativo</button></header>
 <main>
 {tab==='inicio'&&<><section className="hero"><div className="hero-copy"><span className="eyebrow">ENSINO NEUROEDUCACIONAL APLICADO AO TRÂNSITO</span><h1>Ciência, educação e comportamento para um trânsito mais humano e seguro.</h1><p>O ENAT desenvolve formação, conhecimento, pesquisa e soluções educacionais voltadas à compreensão do fator humano no trânsito.</p><div className="actions"><button className="primary" onClick={()=>setTab('cursos')}>Conheça os cursos</button><button className="secondary" onClick={()=>setTab('interesse')}>Tenho interesse</button></div></div><div className="hero-card"><div className="brain">🧠</div><h2>ENAT HSI</h2><p>Integração entre neuroeducação, segurança viária, comportamento humano e formação profissional.</p></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">CONHEÇA</span><h2>Um ecossistema de conhecimento</h2></div><p>Conteúdo institucional, cursos, artigos, notícias, pesquisas e participação da comunidade.</p></div><div className="cards four"><article><b>🧠 Neuroeducação</b><p>Aplicação de conhecimentos sobre aprendizagem, cognição e comportamento.</p></article><article><b>🚗 Segurança viária</b><p>Foco no fator humano e na construção de atitudes mais seguras.</p></article><article><b>🔬 Pesquisa</b><p>Produção e divulgação de conhecimento aplicado ao trânsito.</p></article><article><b>👥 Formação</b><p>Cursos, palestras e experiências para profissionais e instituições.</p></article></div></section></>}
 {tab==='sobre'&&<section className="section prose"><span className="eyebrow">O ENAT</span><h1>Ensino Neuroeducacional Aplicado ao Trânsito</h1><p>O ENAT é uma proposta de educação e desenvolvimento humano aplicada ao contexto do trânsito, com atenção aos processos cognitivos, emocionais, comportamentais e sociais que influenciam decisões e atitudes.</p><div className="cards three"><article><h3>Missão</h3><p>Promover conhecimento, formação e inovação para compreender e transformar o comportamento humano no trânsito por meio da educação e da ciência.</p></article><article><h3>Visão</h3><p>Ser referência em neuroeducação aplicada ao trânsito, conectando formação profissional, pesquisa, tecnologia e segurança viária.</p></article><article><h3>Valores</h3><p>Vida, ética, responsabilidade, ciência, respeito, humanização, educação contínua, inovação e compromisso social.</p></article></div><h2>Uma abordagem centrada no ser humano</h2><p>O ENAT busca aproximar o conhecimento científico da prática educacional, valorizando a formação de profissionais capazes de perceber riscos, tomar decisões responsáveis e atuar de forma humanizada.</p></section>}
 {tab==='cursos'&&<section className="section"><span className="eyebrow">FORMAÇÃO</span><h1>Cursos ENAT</h1>{courses.length?<div className="cards three">{courses.map(c=><article key={c.id}><span className="tag">{c.category||'ENAT'}</span><h3>{c.name}</h3><p>{c.summary||c.nature}</p><small>{c.hours?`${c.hours} horas · `:''}{c.modality}</small><button className="text-button" onClick={()=>setTab('interesse')}>Tenho interesse →</button></article>)}</div>:<div className="empty"><h3>Novas turmas em breve</h3><p>Cadastre seu interesse para receber informações sobre os próximos cursos, palestras e eventos.</p><button className="primary" onClick={()=>setTab('interesse')}>Cadastrar interesse</button></div>}</section>}
 {tab==='artigos'&&<section className="section"><span className="eyebrow">CONHECIMENTO ENAT</span><h1>Artigos & Notícias</h1>{editorial.length?<div className="cards two">{editorial.map(x=><article key={x.id}>{x.image_url&&<img src={x.image_url} alt=""/>}<span className="tag">{x.kind==='news'?'NOTÍCIA':'ARTIGO'}</span><h3>{x.title}</h3><p>{x.summary}</p><small>{x.author_name||'ENAT'}{x.category?` · ${x.category}`:''}</small></article>)}</div>:<div className="empty"><h3>O conhecimento ENAT está crescendo</h3><p>Em breve esta área reunirá artigos, pesquisas, ensaios, entrevistas e notícias publicados pelo ENAT e por colaboradores convidados.</p></div>}</section>}
 {tab==='interesse'&&<section className="section narrow"><span className="eyebrow">PARTICIPE</span><PublicForm kind="interest" title="Quero participar do ENAT" subtitle="Cadastre seu interesse em cursos, palestras, workshops, pesquisas ou parcerias.">{({form,set})=><><Field label="Nome" name="name" value={form.name} onChange={v=>set('name',v)} required/><Field label="E-mail" name="email" type="email" value={form.email} onChange={v=>set('email',v)} required/><Field label="WhatsApp" name="phone" value={form.phone} onChange={v=>set('phone',v)}/><Field label="Cidade" name="city" value={form.city} onChange={v=>set('city',v)}/><Field label="UF" name="state" value={form.state} onChange={v=>set('state',v)}/><Field label="Profissão" name="profession" value={form.profession} onChange={v=>set('profession',v)}/><Field label="Instituição" name="institution" value={form.institution} onChange={v=>set('institution',v)}/><label className="field"><span>Área de interesse *</span><select value={form.subject||''} onChange={e=>set('subject',e.target.value)} required><option value="">Selecione</option><option>Cursos</option><option>Palestras</option><option>Workshops</option><option>Formação de instrutores</option><option>Neuroeducação</option><option>Neurociência aplicada ao trânsito</option><option>Pesquisas</option><option>Eventos</option><option>Parcerias institucionais</option></select></label><Field label="Mensagem" name="summary" type="textarea" value={form.summary} onChange={v=>set('summary',v)} placeholder="Conte brevemente o que você procura no ENAT."/></>}</PublicForm></section>}
 {tab==='publicar'&&<section className="section narrow"><span className="eyebrow">COMUNIDADE ENAT</span><PublicForm kind="article_submission" title="Publique seu conhecimento no ENAT" subtitle="Envie um artigo, pesquisa, ensaio ou relato. Todo material passa por análise editorial antes de qualquer publicação.">{({form,set,files,setFiles,removeFile})=><><Field label="Nome do autor" name="name" value={form.name} onChange={v=>set('name',v)} required/><Field label="E-mail" name="email" type="email" value={form.email} onChange={v=>set('email',v)} required/><Field label="Instituição" name="institution" value={form.institution} onChange={v=>set('institution',v)}/><Field label="Título" name="title" value={form.title} onChange={v=>set('title',v)} required/><Field label="Categoria" name="category" value={form.category} onChange={v=>set('category',v)} placeholder="Ex.: Neuroeducação, Segurança viária, Pesquisa"/><Field label="Resumo" name="summary" type="textarea" value={form.summary} onChange={v=>set('summary',v)} required/><Field label="Texto / proposta" name="content" type="textarea" value={form.content} onChange={v=>set('content',v)} required/><AttachmentField files={files} setFiles={setFiles} removeFile={removeFile}/></>}</PublicForm></section>}
 {tab==='contato'&&<section className="section narrow"><span className="eyebrow">FALE CONOSCO</span><PublicForm kind="contact" title="Entre em contato" subtitle="Use este formulário para informações, convites, parcerias, imprensa ou outras demandas institucionais.">{({form,set})=><><Field label="Nome" name="name" value={form.name} onChange={v=>set('name',v)} required/><Field label="E-mail" name="email" type="email" value={form.email} onChange={v=>set('email',v)} required/><Field label="Telefone / WhatsApp" name="phone" value={form.phone} onChange={v=>set('phone',v)}/><Field label="Assunto" name="subject" value={form.subject} onChange={v=>set('subject',v)} required/><Field label="Mensagem" name="content" type="textarea" value={form.content} onChange={v=>set('content',v)} required/></>}</PublicForm></section>}
 </main><footer className="portal-footer"><BrandingENAT variant="footer"/><div><strong>ENAT — Ensino Neuroeducacional Aplicado ao Trânsito</strong><p>Ciência, educação e humanização para um trânsito mais seguro.</p></div><button onClick={()=>navigate('/login')}>Acesso administrativo</button></footer></div>;
}
