import { useEffect, useState } from "react";
import { changeMyPassword, createAdminUser, deleteAdminUser, listAdminUsers, updateAdminUser } from "../lib/authApi";
import { useAuth } from "../context/AuthContext";
import "./UsuariosENAT.css";

const empty={username:"",display_name:"",password:"",role:"operador",active:true};
export function UsuariosENAT(){
 const {profile}=useAuth(); const [users,setUsers]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [myPassword,setMyPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const load=async()=>{try{const r=await listAdminUsers();setUsers(r.users||[])}catch(e){setError(e.message)}}; useEffect(()=>{if(profile?.role==="admin")load()},[profile?.role]);
 if(profile?.role!=="admin")return <main className="users-page"><section className="users-card"><h1>Acesso restrito</h1><p>Somente administradores podem gerenciar usuários.</p></section></main>;
 const submit=async(e)=>{e.preventDefault();setBusy(true);setError("");setMessage("");try{if(editing){await updateAdminUser(editing.id,{display_name:form.display_name,role:form.role,active:form.active,password:form.password||undefined});setMessage("Usuário atualizado.")}else{await createAdminUser(form);setMessage("Usuário criado e autorizado.")}setForm(empty);setEditing(null);await load()}catch(err){setError(err.message)}finally{setBusy(false)}};
 const edit=(u)=>{setEditing(u);setForm({username:u.username,display_name:u.display_name,password:"",role:u.role,active:u.active})};
 const remove=async(u)=>{if(!confirm(`Excluir o acesso de ${u.username}?`))return;try{await deleteAdminUser(u.id);setMessage("Acesso excluído.");await load()}catch(e){setError(e.message)}};
 const changePassword=async(e)=>{e.preventDefault();if(!myPassword)return;setBusy(true);setError("");try{await changeMyPassword(myPassword);setMyPassword("");setMessage("Sua senha foi alterada com sucesso.")}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <main className="users-page"><div className="users-head"><div><span className="eyebrow">CENTRAL ENAT HSI · SEGURANÇA</span><h1>Usuários e autorizações</h1><p>Cadastre quem pode entrar na Central e defina o nível de acesso.</p></div></div><div className="users-grid"><section className="users-card"><h2>{editing?"Editar usuário":"Novo usuário"}</h2><form onSubmit={submit}><label>Usuário<input value={form.username} disabled={!!editing} onChange={e=>setForm({...form,username:e.target.value.toLowerCase()})} placeholder="ex.: joao" required={!editing}/></label><label>Nome de exibição<input value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})} placeholder="Nome completo" required/></label><label>{editing?"Nova senha (opcional)":"Senha"}<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo de 6 caracteres" required={!editing}/></label><label>Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Administrador</option><option value="operador">Operador</option></select></label>{editing&&<label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Usuário ativo e autorizado</label>}<div className="form-actions"><button disabled={busy}>{busy?"Salvando…":editing?"Salvar alterações":"Criar usuário"}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</div></form></section><section className="users-card"><h2>Minha senha</h2><p>Troque a senha do usuário atualmente conectado.</p><form onSubmit={changePassword}><label>Nova senha<input type="password" value={myPassword} onChange={e=>setMyPassword(e.target.value)} minLength={6} placeholder="Mínimo de 6 caracteres"/></label><button disabled={busy}>ALTERAR MINHA SENHA</button></form></section></div>{message&&<div className="users-ok">{message}</div>}{error&&<div className="users-error">{error}</div>}<section className="users-card table-card"><div className="table-title"><h2>Acessos cadastrados</h2><span>{users.length} usuário(s)</span></div><div className="users-table"><div className="tr th"><span>Usuário</span><span>Nome</span><span>Perfil</span><span>Status</span><span>Ações</span></div>{users.map(u=><div className="tr" key={u.id}><span><b>{u.username}</b></span><span>{u.display_name}</span><span>{u.role==="admin"?"Administrador":"Operador"}</span><span className={u.active?"active":"inactive"}>{u.active?"Ativo":"Inativo"}</span><span className="actions"><button onClick={()=>edit(u)}>Editar</button><button className="danger" onClick={()=>remove(u)}>Excluir</button></span></div>)}</div></section></main>;
}
