import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import "./BrandingENAT.css";
const DB_NAME="enat-certificate-brand",STORE_NAME="assets",KEY="logos",LEGACY_ORIGIN="https://enat-hsi-1mf2.vercel.app";
function readLegacy(){try{return JSON.parse(localStorage.getItem("enat_certificate_brand_v2")||"{}")}catch{return {}}}
function readIndexedBrand(){return new Promise(resolve=>{if(!window.indexedDB)return resolve({});let r;try{r=indexedDB.open(DB_NAME,1)}catch{return resolve({})}r.onupgradeneeded=()=>{try{if(!r.result.objectStoreNames.contains(STORE_NAME))r.result.createObjectStore(STORE_NAME)}catch{}};r.onsuccess=()=>{try{const q=r.result.transaction(STORE_NAME,"readonly").objectStore(STORE_NAME).get(KEY);q.onsuccess=()=>resolve(q.result||{});q.onerror=()=>resolve({})}catch{resolve({})}};r.onerror=()=>resolve({})})}
function writeIndexedBrand(brand){return new Promise(resolve=>{if(!window.indexedDB)return resolve();let r;try{r=indexedDB.open(DB_NAME,1)}catch{return resolve()}r.onupgradeneeded=()=>{try{if(!r.result.objectStoreNames.contains(STORE_NAME))r.result.createObjectStore(STORE_NAME)}catch{}};r.onsuccess=()=>{try{const tx=r.result.transaction(STORE_NAME,"readwrite");tx.objectStore(STORE_NAME).put(brand,KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>resolve()}catch{resolve()}};r.onerror=()=>resolve()})}
function requestLegacyBrand(){return new Promise(resolve=>{if(window.location.origin===LEGACY_ORIGIN)return resolve({});let iframe,timer;const cleanup=()=>{window.removeEventListener("message",onMessage);if(timer)clearTimeout(timer);if(iframe)iframe.remove()};const onMessage=e=>{if(e.origin!==LEGACY_ORIGIN||e.data?.type!=="ENAT_BRAND_RESPONSE")return;cleanup();resolve(e.data.brand||{})};window.addEventListener("message",onMessage);iframe=document.createElement("iframe");iframe.src=`${LEGACY_ORIGIN}/login`;iframe.title="ENAT branding migration";iframe.setAttribute("aria-hidden","true");iframe.style.cssText="position:fixed;width:1px;height:1px;opacity:0;pointer-events:none;border:0;left:-10px;top:-10px";iframe.onload=()=>iframe.contentWindow?.postMessage({type:"ENAT_BRAND_REQUEST"},LEGACY_ORIGIN);document.body.appendChild(iframe);timer=setTimeout(()=>{cleanup();resolve({})},7000)})}
async function readPublicSettings(){try{if(!supabase)return {};const {data}=await supabase.from("enat_public_content").select("metadata").eq("section_key","site.settings").eq("published",true).maybeSingle();return data?.metadata||{}}catch{return {}}}
export function useENATBranding(){const [brand,setBrand]=useState({enatLogo:"",neuroLogo:""});useEffect(()=>{let alive=true;(async()=>{const settings=await readPublicSettings();const legacy=readLegacy(),stored=await readIndexedBrand();let resolved={enatLogo:settings.enat_logo_url||stored.enatLogo||legacy.enatLogo||"",neuroLogo:settings.neuro_logo_url||stored.neuroLogo||legacy.neuroLogo||""};if(!resolved.enatLogo||!resolved.neuroLogo){const migrated=await requestLegacyBrand();resolved={enatLogo:resolved.enatLogo||migrated.enatLogo||"",neuroLogo:resolved.neuroLogo||migrated.neuroLogo||""};if(resolved.enatLogo||resolved.neuroLogo)await writeIndexedBrand(resolved)}if(alive)setBrand(resolved)})();return()=>{alive=false}},[]);return brand}
export function BrandingENAT({variant="header",className=""}){const {enatLogo,neuroLogo}=useENATBranding();const neuroSrc=neuroLogo||"/favicon-neuro.png";return <div className={`branding-enat branding-${variant} ${className}`} aria-label="Identidade ENAT e Neurociência Aplicada ao Trânsito"><img src={neuroSrc} alt="Neurociência Aplicada ao Trânsito" className="branding-neuro"/><div className="branding-enat-text"><strong>ENAT</strong><small>ENSINO NEUROEDUCACIONAL<br/>APLICADO AO TRÂNSITO</small></div>{enatLogo?<img src={enatLogo} alt="ENAT — Ensino Neuroeducacional Aplicado ao Trânsito" className="branding-enat-logo"/>:null}</div>}
