import { createClient } from "npm:@supabase/supabase-js@2";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(v:any)=>v==null?null:String(v).trim();
const uuid=(v:any)=>typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)?v:null;
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 try{
  const auth=req.headers.get("Authorization")||""; if(!auth.startsWith("Bearer "))throw new Error("Acesso administrativo necessário.");
  const anon=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}});
  const {data:{user},error:ae}=await anon.auth.getUser(); if(ae||!user)throw new Error("Sessão administrativa inválida.");
  const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const {data:profile}=await db.from("admin_profiles").select("id,role,active").eq("id",user.id).maybeSingle(); if(!profile?.active)throw new Error("Usuário sem autorização ativa para a Central ENAT HSI.");
  const b=await req.json();
  const result={courses:0,instructors:0,students:0,certificates:0,skipped:0,errors:[] as string[]};
  if(b.course&&String(b.course.code||"").trim()){
   const c=b.course; const row:any={name:clean(c.name)||"Curso ENAT",code:String(c.code).trim().toUpperCase(),nature:clean(c.nature)||"Curso Livre de Formação e Capacitação",modality:clean(c.modality)||"Online",responsible:clean(c.responsible)||"ENAT — Ensino Neuroeducacional Aplicado ao Trânsito",responsible_role:clean(c.responsible_role||c.responsibleRole)||"Responsável Técnico",author:clean(c.author),author_role:clean(c.author_role||c.authorRole),summary:clean(c.summary),modules:Array.isArray(c.modules)?c.modules:[],active:c.active!==false,version:Number(c.version||1),thumbnail_url:clean(c.thumbnail_url),category:clean(c.category),published:Boolean(c.published),hours:Number(c.hours||0),slug:clean(c.slug)};
   const {data:existing}=await db.from("enat_courses").select("id,version").eq("code",row.code).maybeSingle(); if(existing){row.version=Math.max(Number(existing.version||1)+1,row.version);const {error}=await db.from("enat_courses").update(row).eq("id",existing.id);if(error)result.errors.push(`curso: ${error.message}`);else result.courses=1;}else{const {error}=await db.from("enat_courses").insert({...row,created_by:user.id});if(error)result.errors.push(`curso: ${error.message}`);else result.courses=1;}
  }
  if(Array.isArray(b.instructors))for(const x of b.instructors){const row:any={name:clean(x.name)||clean(x.full_name),qualification:clean(x.qualification)||"Especialista",formation:clean(x.formation)||"Formação não informada",institution:clean(x.institution),registration:clean(x.registration),active:x.active!==false};if(!row.name||!row.formation){result.skipped++;continue}const id=uuid(x.id);let q;if(id){q=await db.from("enat_instructors").upsert({...row,id},{onConflict:"id"});}else{const {data:existing}=await db.from("enat_instructors").select("id").ilike("name",row.name).ilike("formation",row.formation).maybeSingle();q=existing?await db.from("enat_instructors").update(row).eq("id",existing.id):await db.from("enat_instructors").insert(row);}if(q.error)result.errors.push(`docente ${row.name}: ${q.error.message}`);else result.instructors++;}
  let courseId:any=null; if(b.course?.code){const {data:c}=await db.from("enat_courses").select("id").eq("code",String(b.course.code).trim().toUpperCase()).maybeSingle();courseId=c?.id||null;} if(!courseId){const {data:c}=await db.from("enat_courses").select("id").order("created_at",{ascending:false}).limit(1).maybeSingle();courseId=c?.id||null;}
  if(Array.isArray(b.students))for(const x of b.students){const cpf=clean(x.cpf);const row:any={name:clean(x.name)||clean(x.full_name),full_name:clean(x.full_name)||clean(x.name),cpf,credential:clean(x.credential),uf:clean(x.uf),course_id:uuid(x.course_id)||courseId,status:clean(x.status)||"em_espera",active:x.active!==false};if(!row.name||!row.cpf||!row.course_id){result.skipped++;continue}const {data:existing}=await db.from("enat_students").select("id").eq("cpf",row.cpf).eq("active",true).maybeSingle();const q=existing?await db.from("enat_students").update(row).eq("id",existing.id):await db.from("enat_students").insert(row);if(q.error)result.errors.push(`aluno ${row.name}: ${q.error.message}`);else result.students++;}
  if(Array.isArray(b.certificates))for(const x of b.certificates){const code=clean(x.certificate_code||x.code);if(!code){result.skipped++;continue}const row:any={user_id:uuid(x.user_id),course_id:clean(x.course_id),course_title:clean(x.course_title||x.course_name),certificate_code:code,issued_at:x.issued_at||x.created_at||new Date().toISOString(),status:clean(x.status)||"issued",student_name:clean(x.student_name||x.name),student_credential:clean(x.student_credential||x.credential),student_signature:clean(x.student_signature),cpf_hash:clean(x.cpf_hash),course_name:clean(x.course_name||x.course_title),course_nature:clean(x.course_nature||x.nature),hours:x.hours==null?null:Number(x.hours),subjects:Array.isArray(x.subjects)?x.subjects:(x.subjects||null),completion_date:x.completion_date||x.end_date||null,start_date:x.start_date||x.start||null,end_date:x.end_date||x.end||null,responsible:clean(x.responsible),author:clean(x.author),institution_name:clean(x.institution_name),institution_cnpj:clean(x.institution_cnpj),responsible_role:clean(x.responsible_role||x.responsibleRole),modality:clean(x.modality),cancelled_at:x.cancelled_at||null};const {data:existing}=await db.from("enat_certificates").select("id").eq("certificate_code",code).maybeSingle();const q=existing?await db.from("enat_certificates").update(row).eq("id",existing.id):await db.from("enat_certificates").insert(row);if(q.error)result.errors.push(`certificado ${code}: ${q.error.message}`);else result.certificates++;}
  await db.from("enat_course_audit").insert({course_id:courseId,action:"RESTORED_LEGACY_DATA",metadata:{source:"Central ENAT HSI recovery",counts:result},created_by:user.id});
  return json({ok:result.errors.length===0,...result});
 }catch(e){return json({error:String((e as any)?.message||e)},400)}
});
